WIP: 初步翻译tools.ftl
rust-lang-cn/www.rust-lang.org pull request #20
Opened 2019-05-27 14:13 UTC by huangjj27

完成了 #8 的翻译, 但自觉还有些拗口, 需要校对给点建议!

2019-05-31 03:14 UTC, b41sh requested changes

2019-05-31 03:14 UTC, b41sh commented on locales/zh-CN/tools.ftl
> +tools-editor-support-heading = 一流编辑器支持
支持主流编辑器

2019-05-31 03:14 UTC, b41sh commented on locales/zh-CN/tools.ftl
> +        <a href="https://github.com/rust-lang/rls">Rust Language Server,/a>。
无论您喜欢使用命令行，还是富图形编辑器写代码，都可以为您选择的编辑器提供Rust集成。或者您可以使用<a href="https://github.com/rust-lang/rls"> Rust语言服务器</a>构建自己的编辑器。

2019-05-31 03:14 UTC, b41sh commented on locales/zh-CN/tools.ftl
> +        立于巨人之肩，您和团队将远离繁琐重复，专注革新。
拥有数以万计的软件包，<a href="https://crates.io">crates.io</a>很可能是您正在寻找的解决方案。站在巨人的肩膀上，让您的团队远离重复，专注创新。

2019-05-31 03:14 UTC, b41sh commented on locales/zh-CN/tools.ftl
> +        是Rust的通用测试方案：测试用例既可写在功能代码之后，也可放在独立文件。任你测试需求三千，尽可满足。
你 -> 您
任你测试需求三千，尽可满足。-> 它为所有测试需求提供解决方案。

2019-05-31 03:14 UTC, b41sh commented on locales/zh-CN/tools.ftl
> +        有了这些现代化构建接口，无需为平台定制构建脚本。
就可以编译到WIndows、Linux、OSX或Web编译目标。-> 您的代码就可以编译到Windows，Linux，OSX和Web。 
有了这些现代化构建接口，无需为平台定制构建脚本。 -> 支持现代界面的所有部分，无需定制构建文件。

2019-05-31 03:14 UTC, b41sh commented on locales/zh-CN/tools.ftl
>  tools-automation-clippy-description = <i>“It looks like you’re writing an
It looks like you’re writing an Iterator. -> 看起来你正在写一个迭代器

2019-05-31 03:14 UTC, b41sh commented on locales/zh-CN/tools.ftl
> +        Iterator.”</i> <br> Clippy帮助开发者写出理想代码，无论处于何种开发水平。这保证了代码规范。
Clippy帮助所有经验级别的开发人员写出符合习惯代码，并强制执行标准。

2019-05-31 03:14 UTC, b41sh commented on locales/zh-CN/tools.ftl
> +tools-build-heading = 构建以迅猛
良好的构建体验

2019-05-31 15:44 UTC, huangjj27 commented on locales/zh-CN/tools.ftl
> +tools-editor-support-heading = 一流编辑器支持
“First-class editor support”这里的“First class”应该是修饰“support”？

2019-05-31 15:45 UTC, huangjj27 commented on locales/zh-CN/tools.ftl
>  tools-automation-clippy-description = <i>“It looks like you’re writing an
编译器提示文本， 也许不翻译会更好？

2019-05-31 18:27 UTC, aaranxu commented on locales/zh-CN/tools.ftl
> +tools-editor-support-description = 无论你喜欢用命令行, 还是富图形编辑器, Rust都可以
Rust 和后面中文加上空格，通常英文单词一般都与前后文字间隔一个空格

2019-05-31 18:27 UTC, aaranxu commented on locales/zh-CN/tools.ftl
> +tools-build-heading = 构建以迅猛
这里语句表达可以再调整下

2019-05-31 18:27 UTC, aaranxu commented on locales/zh-CN/tools.ftl
> +tools-build-test-description = 有了rust的优秀测试工具, 你将对编码重拾信心. <code class="nowrap">cargo test</code>
`Rust`，在文字表述中，一般都不用 `rust`，即第一个字母都是大写形式

2019-05-31 18:27 UTC, aaranxu commented on locales/zh-CN/tools.ftl
> +tools-editor-support-heading = 一流编辑器支持
```suggestion
tools-editor-support-heading = 拥有主流编辑器支持
```

2019-05-31 18:27 UTC, aaranxu commented on locales/zh-CN/tools.ftl
> +tools-editor-support-description = 无论你喜欢用命令行，还是富图形编辑器，Rust都可以
```suggestion
tools-editor-support-description = 无论你喜欢用命令行，还是可视化编辑器，你选用的编辑器都可以集成 Rust 的支持。
```

2019-05-31 18:27 UTC, aaranxu commented on locales/zh-CN/tools.ftl
> +        与之整合。甚至，你可以自行编译
```suggestion
        或者您也可以使用<a href="https://github.com/rust-lang/rls">Rust 语言服务（Rust Language Server，RLS）</a> 来构建自己的编辑器。
```

2019-05-31 18:27 UTC, aaranxu commented on locales/zh-CN/tools.ftl
> +        <a href="https://github.com/rust-lang/rls">Rust Language Server,/a>。
```suggestion
```

2019-05-31 18:27 UTC, aaranxu commented on locales/zh-CN/tools.ftl
> +tools-build-heading = 构建以迅猛
```suggestion
tools-build-heading = 良好的构建体验
```

2019-05-31 18:27 UTC, aaranxu commented on locales/zh-CN/tools.ftl
> +tools-build-description = Cargo用于构建Rust应用，将常用命令集于一身，而无需模板。
```suggestion
tools-build-description = Cargo 是 Rust 的构建工具，将常用命令集于一身，而无需引入其他命令。
```

2019-05-31 18:27 UTC, aaranxu commented on locales/zh-CN/tools.ftl
> +tools-build-install-description = 库成千上百，尽在<a href="https://crates.io">crates.io</a>。
```suggestion
tools-build-install-description = <a href="https://crates.io">crates.io</a> 上拥有成千上万的软件包，您想要的解决方案在这里几乎都能找到。
```

意译本句

2019-05-31 18:27 UTC, aaranxu commented on locales/zh-CN/tools.ftl
> +        立于巨人之肩，您和团队将远离繁琐重复，专注革新。
```suggestion
        站在巨人的肩膀上，让您的团队远离重复，专注创新。
```

2019-05-31 18:27 UTC, aaranxu commented on locales/zh-CN/tools.ftl
> +tools-build-test-description = 有了rust的优秀测试工具，你将对编码重拾信心。<code class="nowrap">cargo test</code>
```suggestion
tools-build-test-description = 利用 Rust 出色的测试工具，您做得到对代码充满信心。<code class="nowrap">cargo test</code>
```

2019-05-31 18:27 UTC, aaranxu commented on locales/zh-CN/tools.ftl
> +        是Rust的通用测试方案：测试用例既可写在功能代码之后，也可放在独立文件。任你测试需求三千，尽可满足。
```suggestion
        是 Rust 统一的测试方案。测试代码既可写在功能代码之后，也可放在独立文件，这提供了一个解决方案针对所有的测试需求。
```

2019-05-31 18:27 UTC, aaranxu commented on locales/zh-CN/tools.ftl
> +        可为各平台构建精炼的可执行文件。仅需一行命令，就可以编译到WIndows、Linux、OSX或Web编译目标。
```suggestion
        可为各个平台构建精炼的可执行文件。仅需一行命令，您的代码就可以针对 Windows、Linux、macOS 和 Web 进行编译。
```

2019-05-31 18:27 UTC, aaranxu commented on locales/zh-CN/tools.ftl
> +        有了这些现代化构建接口，无需为平台定制构建脚本。
```suggestion
        支持全部现代平台接口，不需要定制构建文件。
```

2019-05-31 18:27 UTC, aaranxu commented on locales/zh-CN/tools.ftl
> +tools-automation-heading = 用自动化加速
```suggestion
tools-automation-heading = 利用自动化加速
```

2019-05-31 18:27 UTC, aaranxu commented on locales/zh-CN/tools.ftl
> +tools-automation-description = Rust的工业级工具集让协作更加无畏，使团队更加专注于重要的任务。
```suggestion
tools-automation-description = Rust 的工业级工具使协作勇往直前，让团队专注于重要的任务。
```

2019-05-31 18:27 UTC, aaranxu commented on locales/zh-CN/tools.ftl
> +tools-automation-rustfmt-description = Rustfmt自动格式化Rust代码，代码更易读，更易写，更易维护。
```suggestion
tools-automation-rustfmt-description = Rustfmt 自动格式化 Rust 代码，使代码更容易阅读、编写和维护。
```

2019-05-31 18:27 UTC, aaranxu commented on locales/zh-CN/tools.ftl
> +        最重要一点：再也不需要为空格或者括号的问题争论。
```suggestion
        最重要一点：再也不需要为空格或大括号位置的问题争论。
```

2019-05-31 18:27 UTC, aaranxu commented on locales/zh-CN/tools.ftl
> +tools-automation-rustfmt-link = 项目仓库
```suggestion
tools-automation-rustfmt-link = 前往项目仓库
```

2019-05-31 18:27 UTC, aaranxu commented on locales/zh-CN/tools.ftl
>  tools-automation-clippy-description = <i>“It looks like you’re writing an
```suggestion
tools-automation-clippy-description = <i>“看起来您正在编写重复代码。”</i><br>
```

2019-05-31 18:27 UTC, aaranxu commented on locales/zh-CN/tools.ftl
> +        Iterator.”</i> <br> Clippy帮助开发者写出理想代码，无论处于何种开发水平。这保证了代码规范。
```suggestion
        Clippy 帮助开发者编写出惯用代码并强制执行标准，无论开发者处于何种开发水平。
```

2019-05-31 18:27 UTC, aaranxu commented on locales/zh-CN/tools.ftl
> +tools-automation-clippy-link = 项目仓库
```suggestion
tools-automation-clippy-link = 前往项目仓库
```

2019-05-31 18:27 UTC, aaranxu commented on locales/zh-CN/tools.ftl
> +tools-automation-cargo-doc-description = Cargo文档构建器从不忘记为API标注文档。
```suggestion
tools-automation-cargo-doc-description = Cargo 文档构建器使得没有 API 不存在文档。
```

2019-05-31 18:27 UTC, aaranxu commented on locales/zh-CN/tools.ftl
> +tools-automation-cargo-doc-link = 前往docs.rs
```suggestion
tools-automation-cargo-doc-link = 前往 docs.rs
```

2019-05-31 18:27 UTC, aaranxu commented on locales/zh-CN/tools.ftl
> +        你既可以在本地浏览 <code class="nowrap">cargo doc</code>，也可到
```suggestion
        您可以通过 <code class="nowrap">cargo doc</code> 将文档生成在本地，
```

2019-05-31 18:27 UTC, aaranxu commented on locales/zh-CN/tools.ftl
> +        <a href="https://docs.rs">docs.rs</a>在线浏览公开库。
```suggestion
        还可以通过 <a href="https://docs.rs">docs.rs</a> 在线获得公开 crate 的文档。
```

2019-06-01 05:42 UTC, huangjj27 reviewed
一些细节的细微调整

2019-06-01 05:42 UTC, huangjj27 commented on locales/zh-CN/tools.ftl
> +tools-build-test-description = 利用 Rust 出色的测试工具，您做得到对代码充满信心。<code class="nowrap">cargo test</code>
```suggestion
tools-build-test-description = 利用 Rust 出色的测试工具，您将对代码充满信心。<code class="nowrap">cargo test</code>
```

原文并没有“做得到”这样的字眼。个人认为，结合语境，“Bring confidence” 带来信心可以翻译为重拾信心，或者充满自信/信心

2019-06-01 05:42 UTC, huangjj27 commented on locales/zh-CN/tools.ftl
> +        最重要一点：再也不需要为空格或大括号位置的问题争论。
```suggestion
        最重要一点：再也不需要为空格或大括号位置问题争论。
```

减少连词以提高阅读体验

2019-06-01 05:42 UTC, huangjj27 commented on locales/zh-CN/tools.ftl
> +tools-automation-clippy-description = <i>“看起来您正在编写重复代码。”</i><br>
```suggestion
tools-automation-clippy-description = <i>“似乎您在编写重复代码。”</i><br>
```
修改措辞

2019-06-01 12:20 UTC, aaranxu commented on locales/zh-CN/tools.ftl
> +tools-automation-cargo-doc-description = Cargo 文档构建器使得没有 API 不存在文档。
```suggestion
tools-automation-cargo-doc-description = Cargo 文档构建器生成文档的功能强大而又便捷，所以没有 API 不存在文档的情况。
```

2019-06-01 12:21 UTC, aaranxu commented on locales/zh-CN/tools.ftl
> +tools-automation-cargo-doc-description = Cargo 文档构建器使得没有 API 不存在文档。
尽一步调整语句，英文原句也是有问题的，句子缺少内容，现在根据上下文补充完整。

2019-06-02 06:23 UTC, huangjj27 commented
如果没有明显的问题，就合并咯？ @b41sh @aaranxu

2019-06-02 07:33 UTC, aaranxu commented
再次检查了一遍，可以合并了，你们也再次确认下 @b41sh @ZhangHanDong

2019-06-02 10:57 UTC, OlingCat commented
LGTM

2019-06-02 15:31 UTC, b41sh commented
LGTM

2019-06-03 08:15 UTC, merged