Translate locales/zh-CN/homepage.ftl to Chinese
rust-lang-cn/www.rust-lang.org pull request #23
Opened 2019-05-27 17:14 UTC by aaranxu

2019-05-27 17:40 UTC, aaranxu reviewed
#5

2019-05-28 14:10 UTC, OlingCat requested changes

2019-05-28 14:10 UTC, OlingCat commented on locales/zh-CN/homepage.ftl
> +tagline =  一门能让每个人都构建出{ $linebreak }可靠又高效的软件的语言。
```suggestion
tagline =  让每个人都能构建出{ $linebreak }可靠而高效的软件。
```
这里其实可以不用强调语言。

2019-05-28 14:10 UTC, OlingCat commented on locales/zh-CN/homepage.ftl
> +production-blurb = 目前全世界已经有数百家公司在生产环境中使用 Rust， 以达到快速、资源
```suggestion
production-blurb = 全世界已有数百家公司在生产环境中使用 Rust，以达到快速、节省资源、跨平台的目的。
```

2019-05-28 14:10 UTC, OlingCat commented on locales/zh-CN/homepage.ftl
> +         消耗低、解决跨平台的目的。这包括著名且受欢迎的软件，例如 <a href="https://hacks.mozilla.org/2017/08/inside-a-super-fast-css-engine-quantum-css-aka-stylo/">Firefox</a>、
```suggestion
         其中包括很多著名且受欢迎的软件，例如 <a href="https://hacks.mozilla.org/2017/08/inside-a-super-fast-css-engine-quantum-css-aka-stylo/">Firefox</a>、
```

2019-05-28 14:10 UTC, OlingCat commented on locales/zh-CN/homepage.ftl
> +         和 <a href="https://blog.cloudflare.com/cloudflare-workers-as-a-serverless-rust-platform/">Cloudflare</a>，
```suggestion
         和 <a href="https://blog.cloudflare.com/cloudflare-workers-as-a-serverless-rust-platform/">Cloudflare</a>
```

2019-05-28 14:10 UTC, OlingCat commented on locales/zh-CN/homepage.ftl
> +         都使用 Rust。<strong>从初创公司到大型企业，从嵌入式设备到可扩展的 Web 服务，Rust 都完全适合。</strong>
```suggestion
         都在使用 Rust。<strong>从初创公司到大型企业，从嵌入式设备到可扩展的 Web 服务，Rust 都完全合适。</strong>
```

2019-05-28 14:10 UTC, OlingCat commented on locales/zh-CN/homepage.ftl
> +production-learn-more = 学习更多
```suggestion
production-learn-more = 了解更多
```
这里取「了解」的意思，下同。

2019-05-28 14:10 UTC, OlingCat commented on locales/zh-CN/homepage.ftl
> +production-testimonial-npm-attribution = Chris Dickinson， 来自 npm 公司的工程师
```suggestion
production-testimonial-npm-attribution = Chris Dickinson，来自 npm 公司的工程师
```

2019-05-28 14:10 UTC, OlingCat commented on locales/zh-CN/homepage.ftl
> +production-testimonial-yelp = 所有的文档、工具和社区都相当棒——您拥有帮助您顺利编写 Rust 代码的所有工具。
```suggestion
production-testimonial-yelp = 所有的文档、工具和社区都相当棒——您拥有助您顺利编写 Rust 代码的所有工具。
```

2019-05-28 14:10 UTC, OlingCat commented on locales/zh-CN/homepage.ftl
> +          Rust 能胜任性能要求特别高的服务，能运行在嵌入式设备，并能轻松地和其他语言集成。
```suggestion
          Rust 能胜任性能要求特别高的服务，能运行在嵌入式设备上，并能轻松与其他语言集成。
```

2019-05-28 14:10 UTC, OlingCat commented on locales/zh-CN/homepage.ftl
> +language-values-reliability-blurb = Rust 的丰富类型系统和所有权模型保证了内存安全和线程安全&mdash;&mdash;使您能够在编译期消除许多类型错误。
```suggestion
language-values-reliability-blurb = Rust 丰富的类型系统和所有权模型保证了内存安全和线程安全&mdash;&mdash;您能够在编译期消除许多类型错误。
```

2019-05-28 14:10 UTC, OlingCat commented on locales/zh-CN/homepage.ftl
> +language-values-productivity = 生产率
```suggestion
language-values-productivity = 生产力
```

2019-05-28 14:10 UTC, OlingCat commented on locales/zh-CN/homepage.ftl
> +language-values-productivity-blurb = Rust 拥有出色的文档、友好的编译器和有用的错误提示信息，
```suggestion
language-values-productivity-blurb = Rust 拥有出色的文档、友好的编译器和清晰的错误提示信息，
```
这里可以意译一下。

2019-05-28 14:10 UTC, OlingCat commented on locales/zh-CN/homepage.ftl
> +          具有自动补全和类型检查的智能的多编辑器支持，以及自动格式化程序，等等。
```suggestion
          带有智能的自动补全和类型检查的多编辑器支持，以及自动格式化程序等等。
```

2019-05-28 14:10 UTC, OlingCat commented on locales/zh-CN/homepage.ftl
> +domains-blurb = 在 2018 年，Rust 社区决定了在少数不同的领域中完善编程的实践内容
```suggestion
domains-blurb = 2018 年，Rust 社区决定在一些不同的领域中提升编程体验
```

2019-05-28 14:10 UTC, OlingCat commented on locales/zh-CN/homepage.ftl
> +          （参考<a href="https://blog.rust-lang.org/2018/03/12/roadmap.html">2018年路线图</a>）。
```suggestion
          （参见 <a href="https://blog.rust-lang.org/2018/03/12/roadmap.html">2018 年路线图</a>）。
```

2019-05-28 14:10 UTC, OlingCat commented on locales/zh-CN/homepage.ftl
> +          对于这些，您可以找到许多高质量的 crate 和一些如何入门的精彩指南。
```suggestion
          对此，您可以找到许多高质量的 crate 和一些精彩的入门指南。
```

2019-05-28 14:10 UTC, OlingCat commented on locales/zh-CN/homepage.ftl
> +domains-learn-more = 学习更多
```suggestion
domains-learn-more = 了解更多
```

2019-05-28 14:10 UTC, OlingCat commented on locales/zh-CN/homepage.ftl
> +domains-cli-blurb = 使用 Rust 强大的生态系统快速实现 CLI 工具。Rust 可帮助您放心维护和轻松分发应用程序。
```suggestion
domains-cli-blurb = 使用 Rust 强大的生态系统快速实现 CLI 工具。Rust 可助您放心维护，轻松分发应用程序。
```

2019-05-28 14:10 UTC, OlingCat commented on locales/zh-CN/homepage.ftl
> +          使用 webpack 打包，然后你可以感受到惊人的速度了。
```suggestion
          使用 webpack 打包，然后你就可以感受到惊人的速度了。
```

2019-05-28 14:10 UTC, OlingCat commented on locales/zh-CN/homepage.ftl
> +get-involved-read-rust = 阅读 Rust
```suggestion
get-involved-read-rust = 阅读 Rust 文档
```

2019-05-28 14:10 UTC, OlingCat commented on locales/zh-CN/homepage.ftl
> +get-involved-contribute-blurb = Rust 是真正由社区驱动的项目，我们欢迎业余爱好者和专业用户，从新人到经验丰富的专业人士我们都欢迎。参与项目，协助我们，让 Rust 变得更好！
```suggestion
get-involved-contribute-blurb = Rust 是真正由社区驱动的项目，我们欢迎业余爱好者和专业用户，从新手到经验丰富的专业人士我们都欢迎。参与项目，协助我们，让 Rust 变得更好！
```

2019-05-29 11:24 UTC, aaranxu commented on locales/zh-CN/homepage.ftl
> +         消耗低、解决跨平台的目的。这包括著名且受欢迎的软件，例如 <a href="https://hacks.mozilla.org/2017/08/inside-a-super-fast-css-engine-quantum-css-aka-stylo/">Firefox</a>、
“而” 改成 “且”，表并列关系

2019-05-29 11:34 UTC, OlingCat commented on locales/zh-CN/homepage.ftl
> +production-testimonial-npm-attribution = Chris Dickinson， 来自 npm 公司的工程师
这个空格没必要存在吧？

2019-05-29 11:34 UTC, OlingCat commented on locales/zh-CN/homepage.ftl
> +production-testimonial-yelp = 所有的文档、工具和社区都相当棒——您拥有帮助您顺利编写 Rust 代码的所有工具。
这里省一个字，虽然区别不大= =

2019-05-29 11:35 UTC, OlingCat commented on locales/zh-CN/homepage.ftl
> +          Rust 能胜任性能要求特别高的服务，能运行在嵌入式设备，并能轻松地和其他语言集成。
不感觉这样更通顺么？

2019-05-29 11:36 UTC, OlingCat commented on locales/zh-CN/homepage.ftl
> +language-values-reliability-blurb = Rust 的丰富类型系统和所有权模型保证了内存安全和线程安全&mdash;&mdash;使您能够在编译期消除许多类型错误。
破折号作进一步解释，不用加「使」这个字。

2019-05-29 11:36 UTC, OlingCat commented on locales/zh-CN/homepage.ftl
> +language-values-productivity = 生产率
印象中这个译法比较常见

2019-05-29 11:37 UTC, OlingCat reviewed
发现有些修改乃没有接受但也没有拒绝，能说下原因么？

2019-05-29 11:38 UTC, OlingCat approved these changes

2019-05-29 11:55 UTC, aaranxu commented
> 发现有些修改乃没有接受但也没有拒绝，能说下原因么？

这次应该都处理完了，刚刚没没看到隐藏项的内容

2019-05-29 12:36 UTC, ZhangHanDong commented
@aaranxu @OlingCat  我review了一下，有一些建议，大家再看看。

2019-05-29 13:10 UTC, OlingCat commented
> @aaranxu @OlingCat 我review了一下，有一些建议，大家再看看。

没有看到啊？

2019-05-29 15:32 UTC, aaranxu commented
> > @aaranxu @OlingCat 我review了一下，有一些建议，大家再看看。
> 
> 没有看到啊？

可能是还没点`完成`

2019-05-30 05:04 UTC, crlf0710 commented on locales/zh-CN/homepage.ftl
> +tagline =  让每个人都能构建出{ $linebreak }可靠而高效的软件。
A language 的部分翻译之后不见啦

2019-05-30 05:07 UTC, crlf0710 commented on locales/zh-CN/homepage.ftl
> +production-testimonial-npm = 我对 Rust 最大的赞美就是它太无聊了，这是令人惊叹的赞美。
考虑"用起来平淡无奇"之类的说法？直接对照中文读者可能不容易读懂。

2019-05-30 05:11 UTC, crlf0710 commented on locales/zh-CN/homepage.ftl
> +production-testimonial-yelp = 所有的文档、工具和社区都相当棒——您拥有助您顺利编写 Rust 代码的所有工具。
这句其实意思似乎是”在你编写 Rust 代码时，你持有获取成功所需要的所有工具(要素)”，另外 tool 和 tooling都翻成工具会让读者难懂=。=改变其中一个比较好。

2019-05-30 05:12 UTC, crlf0710 commented on locales/zh-CN/homepage.ftl
> +language-values-reliability-blurb = Rust 丰富的类型系统和所有权模型保证了内存安全和线程安全&mdash;&mdash;您能够在编译期消除许多类型错误。
类型错误 => 类别/种类 的错误

2019-05-30 05:13 UTC, crlf0710 commented on locales/zh-CN/homepage.ftl
> +          带有智能的自动补全和类型检查的多编辑器支持，以及自动格式化程序等等。
类型检查 => 类型提示

2019-05-30 05:28 UTC, crlf0710 commented on locales/zh-CN/homepage.ftl
> +domains-net-blurb = 可预测的性能，极小的资源损耗，坚如磐石的可靠性。Rust 极其适合网络编程。
网络编程  原文是网络服务

2019-05-30 08:03 UTC, OlingCat commented on locales/zh-CN/homepage.ftl
> +tagline =  让每个人都能构建出{ $linebreak }可靠而高效的软件。
感觉在中文语境下没必要特别指明它是一种语言。

2019-05-30 08:09 UTC, huangjj27 commented on locales/zh-CN/homepage.ftl
> +language-values-reliability-blurb = Rust 丰富的类型系统和所有权模型保证了内存安全和线程安全&mdash;&mdash;您能够在编译期消除许多类型错误。
消除许多类型错误-> 消除各种bug
 bug 也是专业术语，如果要翻译，也许翻译成漏洞好一些？

2019-05-30 08:16 UTC, OlingCat requested changes

2019-05-30 08:16 UTC, OlingCat commented on locales/zh-CN/homepage.ftl
> +production-testimonial-npm = 我对 Rust 最大的赞美就是它太无聊了，这是令人惊叹的赞美。
可以。
```suggestion
production-testimonial-npm = 我对 Rust 最大的赞美就是它用起来平淡无奇，这是令人惊叹的赞美。
```

2019-05-30 08:16 UTC, OlingCat commented on locales/zh-CN/homepage.ftl
> +production-testimonial-yelp = 所有的文档、工具和社区都相当棒——您拥有助您顺利编写 Rust 代码的所有工具。
```suggestion
production-testimonial-yelp = 所有的文档、工具和社区都相当棒——您拥有助您成功编写 Rust 代码的所有要素。
```
还是别扭= =

2019-05-30 08:16 UTC, OlingCat commented on locales/zh-CN/homepage.ftl
> +language-values-reliability-blurb = Rust 丰富的类型系统和所有权模型保证了内存安全和线程安全&mdash;&mdash;您能够在编译期消除许多类型错误。
```suggestion
language-values-reliability-blurb = Rust 丰富的类型系统和所有权模型保证了内存安全和线程安全&mdash;&mdash;您能够在编译期消除多种错误。
```
校对时没看原文= =

2019-05-30 08:16 UTC, OlingCat commented on locales/zh-CN/homepage.ftl
> +          带有智能的自动补全和类型检查的多编辑器支持，以及自动格式化程序等等。
```suggestion
          带有智能的自动补全和类型提示的多编辑器支持，以及自动格式化程序等等。
```

2019-05-30 08:16 UTC, OlingCat commented on locales/zh-CN/homepage.ftl
> +domains-net-blurb = 可预测的性能，极小的资源损耗，坚如磐石的可靠性。Rust 极其适合网络编程。
```suggestion
domains-net-blurb = 可预测的性能，极小的资源损耗，坚如磐石的可靠性。Rust 极其适合网络服务。
```

2019-05-30 11:00 UTC, aaranxu commented on locales/zh-CN/homepage.ftl
> +tagline =  让每个人都能构建出{ $linebreak }可靠而高效的软件。
另外“而”字是否换成其他的表示并列的词汇，比如“且”、“又”、“和”？

“而”字在现代中文语境下一般表示转折关系，虽然古代文言文中也有并列的含义，但现在很少会用“而”表示并列。

2019-05-30 11:04 UTC, aaranxu commented on locales/zh-CN/homepage.ftl
> +tagline =  让每个人都能构建出{ $linebreak }可靠而高效的软件。
我现在再仔细思考下，我觉得还是保留“语言”好点，这句话也相当于给 Rust 起一个基本的概括，让读者一看就知道是一门语言，当然对于熟悉 Rust 的人来说很明确知道这是一门语言，但是官网的受众并不一定局限于开发者，也可以能是新手或者计算机小白。

大家可以对这两种情况都发表下意见。

让每个人都能构建出{ $linebreak }可靠而高效的软件。

2019-05-30 11:37 UTC, aaranxu commented on locales/zh-CN/homepage.ftl
> +domains-net-blurb = 可预测的性能，极小的资源损耗，坚如磐石的可靠性。Rust 极其适合网络编程。
这里采取意译，“适合网络服务”意思也就是用于网络服务的编程，中文一般就称为“网络编程”

2019-05-30 11:37 UTC, aaranxu commented on locales/zh-CN/homepage.ftl
> +domains-net-blurb = 可预测的性能，极小的资源损耗，坚如磐石的可靠性。Rust 极其适合网络编程。
个人建议保留为“网络编程”，感觉对于“网络服务”在这语境下读起来不是特别顺。如果是要改成“网络服务”，那么句子表达成以下形式可能更合适：
Rust 对于网络服务方面很适合。

2019-05-30 11:37 UTC, aaranxu commented on locales/zh-CN/homepage.ftl
> +language-values-reliability-blurb = Rust 丰富的类型系统和所有权模型保证了内存安全和线程安全&mdash;&mdash;您能够在编译期消除许多类型错误。
感觉还要再改改

2019-05-30 11:37 UTC, aaranxu commented on locales/zh-CN/homepage.ftl
> +          带有智能的自动补全和类型检查的多编辑器支持，以及自动格式化程序等等。
inspection  这个单词意思是：检查、检验（a formal or official examination），英文中和 review 的意思同义，“类型提示”在这里仿佛不大符合

2019-05-31 10:40 UTC, aaranxu commented on locales/zh-CN/homepage.ftl
> +tagline =  让每个人都能构建出{ $linebreak }可靠而高效的软件。
```suggestion
tagline =  一门赋予每个人都能构建出{ $linebreak }可靠且高效软件能力的语言。
```

2019-05-31 11:05 UTC, Aimeedeer commented on locales/zh-CN/homepage.ftl
> +tagline =  让每个人都能构建出{ $linebreak }可靠而高效的软件。
赋予你构建{ $linebreak }可靠且高效软件能力的编程语言。

2019-05-31 18:53 UTC, aaranxu commented on locales/zh-CN/homepage.ftl
> +language-values-reliability-blurb = Rust 丰富的类型系统和所有权模型保证了内存安全和线程安全&mdash;&mdash;您能够在编译期消除多种错误。
```suggestion
language-values-reliability-blurb = Rust 丰富的类型系统和所有权模型保证了内存安全和线程安全，让您在编译期能够消除各种各样错误。
```

2019-05-31 18:53 UTC, aaranxu commented on locales/zh-CN/homepage.ftl
> +tagline =  让每个人都能构建出{ $linebreak }可靠而高效的软件。
个人建议保留“一门”、“每个人”

2019-05-31 18:53 UTC, aaranxu commented on locales/zh-CN/homepage.ftl
> +tagline =  让每个人都能构建出{ $linebreak }可靠而高效的软件。
在群里面大家也对这个翻译讨论过，你可以参考下群里面的消息

2019-06-01 04:14 UTC, OlingCat approved these changes

2019-06-01 08:22 UTC, OlingCat requested changes

2019-06-01 08:22 UTC, OlingCat commented on locales/zh-CN/homepage.ftl
> +tagline =  一门赋予每个人都能构建出{ $linebreak }可靠且高效软件能力的语言。
```suggestion
tagline =  赋予每个人{ $linebreak }构建可靠且高效软件能力的语言
```
这样如何？

2019-06-01 12:14 UTC, aaranxu commented on locales/zh-CN/homepage.ftl
> +tagline =  一门赋予每个人都能构建出{ $linebreak }可靠且高效软件能力的语言。
```suggestion
tagline =  一门赋予每个人构建出{ $linebreak }可靠且高效软件能力的语言。
```
我觉得要加上量词 一门。

另外格式方面：
在英文的句子中，我看到他们的做法是想将两句的内容刚好排列成一样长短的上下两个句子的，只是英文单词本身长短不一，导致下面句子比上面句子稍稍长一点。

所以我也建议中文的上下两行句子也尽量做到长短接近，看起来平衡一点。

2019-06-01 13:01 UTC, aaranxu commented on locales/zh-CN/homepage.ftl
> +          带有智能的自动补全和类型提示的多编辑器支持，以及自动格式化程序等等。
```suggestion
          带有智能的自动补全和类型检验的多编辑器支持，以及自动格式化程序等等。
```
翻查过多个短语，还是使用的“检查、检验”的表达：
quality inspection 质量检查
inspection system 检查体系
commodity inspection 商品检验
safety inspection 安全检验
inspection certificate 检验证明书；检查证明

2019-06-02 10:37 UTC, OlingCat commented on locales/zh-CN/homepage.ftl
> +tagline =  一门赋予每个人都能构建出{ $linebreak }可靠且高效软件能力的语言。
可以

2019-06-02 10:37 UTC, OlingCat commented on locales/zh-CN/homepage.ftl
> +          带有智能的自动补全和类型提示的多编辑器支持，以及自动格式化程序等等。
OK

2019-06-02 10:39 UTC, OlingCat commented
@aaranxu 乃自己应用一下 suggestions 然后这个翻译应该就可以合并了。

2019-06-03 11:42 UTC, merged

2019-06-03 12:26 UTC, ZhangHanDong reviewed
一些建议更改

2019-06-03 12:26 UTC, ZhangHanDong commented on locales/zh-CN/homepage.ftl
> +get-started = 入 门
Get Started 我认为翻译为「入门」不合适。
它是有「快速开始」「快速尝试」「快速尝鲜」之意。

2019-06-03 12:26 UTC, ZhangHanDong commented on locales/zh-CN/homepage.ftl
> +production-blurb = 全世界已有数百家公司在生产环境中使用 Rust，以达到快速、节省资源、跨平台的目的。
low-resource  这里不是「节省资源」的意思，虽然Rust可以做到这一点，但这里应该是更加强调适用于「资源不足」「资源低下」的情况。 「节省资源」并没有表达出这一点。再斟酌一下吧。

2019-06-03 12:26 UTC, ZhangHanDong commented on locales/zh-CN/homepage.ftl
> +production-testimonial-npm = 我对 Rust 最大的赞美就是它太无聊了，这是令人惊叹的赞美。
这句话感觉可以在精简一些：「对Rust最大的赞美，就是它太让人无聊了。」

这句话出自npm工程师的一次演讲，上下文大概是：他们部署了Rust服务，结果很快他们就忘记了Rust服务，而且在一年半的时间内生产环境没有引起任何警报。所以，这句话表达的是「Rust太让人无聊」，而不是「Rust太无聊」。

2019-06-03 12:26 UTC, ZhangHanDong commented on locales/zh-CN/homepage.ftl
> +production-testimonial-yelp = 所有的文档、工具和社区都相当棒——您拥有助您顺利编写 Rust 代码的所有工具。
「所有的文档、工具和社区都相当棒——您拥有助您顺利编写 Rust 代码的所有工具。」
感觉不通顺。建议改成：
「文档、工具和社区都相当棒，足以帮助您顺利完成Rust项目。」

2019-06-03 12:26 UTC, ZhangHanDong commented on locales/zh-CN/homepage.ftl
> +language-values-performance-blurb = Rust 速度异常快且内存利用率极高：没有运行时和垃圾回收器。
建议： 

「Rust速度极快，内存利用率极高。Rust没有运行时和垃圾回收器，能胜任性能要求特别高的服务，可运行于嵌入式设备之上，并且能轻松和其他语言集成。」

极快和极高，给人印象深刻，并且把「且」字去了，阅读上去比较上口。就不用英文的那种格式了，去了冒号。

2019-06-03 12:26 UTC, ZhangHanDong commented on locales/zh-CN/homepage.ftl
> +language-values-reliability-blurb = Rust 丰富的类型系统和所有权模型保证了内存安全和线程安全&mdash;&mdash;您能够在编译期消除许多类型错误。
为什么这里有两个 `&mdash;` ? 原文是一个。

2019-06-03 12:26 UTC, ZhangHanDong commented on locales/zh-CN/homepage.ftl
> +          还有一流的工具&mdash;&mdash;集成的包管理器和构建工具，
同上

2019-06-03 12:26 UTC, ZhangHanDong commented on locales/zh-CN/homepage.ftl
> +          带有智能的自动补全和类型检查的多编辑器支持，以及自动格式化程序等等。
这里有点别扭，建议：「智能地自动补全」

2019-06-03 12:26 UTC, ZhangHanDong commented on locales/zh-CN/homepage.ftl
> +domains-wasm-alt = 带拼图元素的齿轮
domains-wasm-alt 这一项其实不翻译应该也可以的，这应该是隐藏展示的

2019-06-03 12:26 UTC, ZhangHanDong commented on locales/zh-CN/homepage.ftl
> +domains-embedded-blurb = 针对资源匮乏的设备？需要低级控制而又不能放弃高级的便利性？那么 Rust 绝对让您满意。
low-level 建议翻译为 「底层」

2019-06-03 12:26 UTC, ZhangHanDong commented on locales/zh-CN/homepage.ftl
> +domains-embedded-blurb = 针对资源匮乏的设备？需要低级控制而又不能放弃高级的便利性？那么 Rust 绝对让您满意。
high-level 也建议换一下，换成「上层抽象」，整句话翻译就是这样：「需要底层控制而又不失上层抽象的便利」。
这正是表达Rust的优势。

2019-06-04 17:34 UTC, OlingCat commented on locales/zh-CN/homepage.ftl
> +          还有一流的工具&mdash;&mdash;集成的包管理器和构建工具，
因为这就是中文里的标准用法啊，两个——可以避免和一混淆。