teams.ftl first version
rust-lang-cn/www.rust-lang.org pull request #27
Opened 2019-05-28 06:11 UTC by readlnh

teams.ftl翻译，不知道是否有人愿意校对，里面涉及的专用词汇有点多，可能有部分内容需要讨论

2019-05-29 10:25 UTC, its404 commented on locales/zh-CN/teams.ftl
> -governance-team-wg-net-async-description = Our goal is to bring async/await onto a path to stabilization and to provide documentation for asynchronous programming.
"bring async/await onto a path to stabilization" -> “将async/await带到稳定的轨道中”，请参考。

2019-05-29 10:30 UTC, its404 commented on locales/zh-CN/teams.ftl
> +governance-team-mods-name = 审核小组
“审核小组” -> “审核团队”？

2019-05-29 10:31 UTC, its404 commented on locales/zh-CN/teams.ftl
> +governance-team-core-name = 核心team
“核心team” -> “核心团队”？

2019-05-29 10:36 UTC, its404 commented on locales/zh-CN/teams.ftl
> +governance-team-wg-embedded-description = 专注于在资源寿险环境以及非传统平台上使用Rust的端到端体验。
"寿险" -> "受限"？

2019-05-29 10:38 UTC, its404 commented on locales/zh-CN/teams.ftl
> +governance-team-crates-io-description = 管理crates.io的运营，发展以及相关政策。
感觉这个development应该是“开发”，开发和维护crates.io

2019-05-29 12:14 UTC, OlingCat commented on locales/zh-CN/teams.ftl
> +governance-team-wg-net-async-description = 我们的目标是将async/await引入到稳定的路径中并为大家提供异步编程的文档。
```suggestion
governance-team-wg-net-async-description = 我们的目标是将 async/await 引入到稳定的轨道上，为大家提供异步编程的文档。
```

2019-05-29 12:15 UTC, OlingCat commented on locales/zh-CN/teams.ftl
> +governance-team-wg-mir-opt-name = MIR优化小组
```suggestion
governance-team-wg-mir-opt-name = MIR 优化小组
```

2019-05-29 12:15 UTC, OlingCat commented on locales/zh-CN/teams.ftl
> +governance-team-wg-mir-opt-description = 编写MIR优化代码和重构MIR来进行更彻底的优化。
```suggestion
governance-team-wg-mir-opt-description = 编写 MIR 优化代码，重构 MIR 以进行更彻底的优化。
```

2019-05-29 12:16 UTC, OlingCat commented on locales/zh-CN/teams.ftl
> +governance-team-wg-net-description = 专注于同步和异步网络代码的端对端体验，使其于本领域不断发展的生态相协调。
```suggestion
governance-team-wg-net-description = 专注于同步和异步网络代码的端对端体验，使其与本领域不断发展的生态相协调。
```

2019-05-29 12:16 UTC, OlingCat commented on locales/zh-CN/teams.ftl
> +governance-team-wg-bindgen-name = Bindgen工作组
```suggestion
governance-team-wg-bindgen-name = Bindgen 工作组
```

2019-05-29 12:16 UTC, OlingCat commented on locales/zh-CN/teams.ftl
> +governance-team-wg-bindgen-description = 用来生成FFI绑定的工具
```suggestion
governance-team-wg-bindgen-description = 用来生成 FFI 绑定的工具
```

2019-05-29 12:16 UTC, OlingCat commented on locales/zh-CN/teams.ftl
> +governance-team-wg-cli-name = 命令行交互(CLI)工作组
```suggestion
governance-team-wg-cli-name = 命令行交互（CLI）工作组
```

2019-05-29 12:17 UTC, OlingCat commented on locales/zh-CN/teams.ftl
> +governance-team-wg-cli-description = 专注于用Rust编写大型/小型CLI应用的端到端体验。
```suggestion
governance-team-wg-cli-description = 专注于用 Rust 编写大型/小型 CLI 应用的端到端体验。
```

2019-05-29 12:18 UTC, OlingCat commented on locales/zh-CN/teams.ftl
> +governance-team-ides-name = IDE和编辑器团队
```suggestion
governance-team-ides-name = IDE 和编辑器团队
```

2019-05-29 13:02 UTC, OlingCat requested changes
以规范中英文间的空格和标点为主，部分语句略有润色。

2019-05-29 13:02 UTC, OlingCat commented on locales/zh-CN/teams.ftl
> +governance-team-ides-description = IDE，编辑器以及一些支持工具诸如Racer和RLS。
```suggestion
governance-team-ides-description = IDE，编辑器以及诸如 Racer 和 RLS 的支持工具。 
```

2019-05-29 13:02 UTC, OlingCat commented on locales/zh-CN/teams.ftl
> +governance-team-clippy-description = 设计和实现Clippy linter
```suggestion
governance-team-clippy-description = 设计和实现 Clippy linter
```

2019-05-29 13:02 UTC, OlingCat commented on locales/zh-CN/teams.ftl
> +governance-team-mods-name = 审核小组
```suggestion
governance-team-mods-name = 审核团队
```

2019-05-29 13:02 UTC, OlingCat commented on locales/zh-CN/teams.ftl
> +governance-team-wg-learning-description = 通过确保rustc指南和api文档的"完整"来使得编译器的学习变得更简单
```suggestion
governance-team-wg-learning-description = 确保 rustc 指南和 API 文档的“完整行”，让学习编译器变得更简单。
```

2019-05-29 13:02 UTC, OlingCat commented on locales/zh-CN/teams.ftl
> +governance-team-cargo-name = Cargo团队
```suggestion
governance-team-cargo-name = Cargo 团队
```

2019-05-29 13:02 UTC, OlingCat commented on locales/zh-CN/teams.ftl
> +governance-team-cargo-description = 设计和实现Cargo
```suggestion
governance-team-cargo-description = 设计和实现 Cargo
```

2019-05-29 13:02 UTC, OlingCat commented on locales/zh-CN/teams.ftl
> +governance-team-core-name = 核心team
```suggestion
governance-team-core-name = 核心团队
```

2019-05-29 13:02 UTC, OlingCat commented on locales/zh-CN/teams.ftl
> +governance-team-rustdoc-name = Rustdoc团队
```suggestion
governance-team-rustdoc-name = Rustdoc 团队
```

2019-05-29 13:02 UTC, OlingCat commented on locales/zh-CN/teams.ftl
> +governance-team-rustdoc-description = 包括Rustdoc和docs.rs在内的文档工具
```suggestion
governance-team-rustdoc-description = 包括 Rustdoc 和 docs.rs 在内的文档工具。
```

2019-05-29 13:02 UTC, OlingCat commented on locales/zh-CN/teams.ftl
> +governance-team-docs-description = 确保Rust有出色的文档
```suggestion
governance-team-docs-description = 确保 Rust 拥有出色的文档。
```

2019-05-29 13:02 UTC, OlingCat commented on locales/zh-CN/teams.ftl
> +governance-team-wg-net-embedded-description = 我们的目标是支持IoT开发。
```suggestion
governance-team-wg-net-embedded-description = 我们的目标是支持 IoT 开发。 
```

2019-05-29 13:02 UTC, OlingCat commented on locales/zh-CN/teams.ftl
> +governance-team-wg-net-web-name = Web基础工作组
```suggestion
governance-team-wg-net-web-name = Web 基础工作组
```

2019-05-29 13:02 UTC, OlingCat commented on locales/zh-CN/teams.ftl
> +governance-team-wg-net-web-description = 我们的目标是提高Rust在web编程中的体验。
```suggestion
governance-team-wg-net-web-description = 我们的目标是提高 Rust 在 Web 编程中的体验。
```

2019-05-29 13:02 UTC, OlingCat commented on locales/zh-CN/teams.ftl
> +governance-team-wg-rls-2-description = 尝试为IDE定制的新编译器架构
```suggestion
governance-team-wg-rls-2-description = 尝试为 IDE 定制新的编译器架构。
```

2019-05-29 13:02 UTC, OlingCat commented on locales/zh-CN/teams.ftl
> +governance-team-devtools-description = Rust开发者工具
```suggestion
governance-team-devtools-description = Rust 开发者工具。
```

2019-05-29 13:02 UTC, OlingCat commented on locales/zh-CN/teams.ftl
> +governance-team-wg-compiler-performance-description = 提升rustc的编译性能(编译耗时)。
```suggestion
governance-team-wg-compiler-performance-description = 提升 rustc 的编译性能（编译耗时）。
```

2019-05-29 13:02 UTC, OlingCat commented on locales/zh-CN/teams.ftl
> +governance-team-wg-rustfmt-name = Rustfmt工作组
```suggestion
governance-team-wg-rustfmt-name = Rustfmt 工作组
```

2019-05-29 13:02 UTC, OlingCat commented on locales/zh-CN/teams.ftl
> +governance-team-wg-rustfmt-description = 设计并实现Rustfmt
```suggestion
governance-team-wg-rustfmt-description = 设计并实现 Rustfmt。
```

2019-05-29 13:02 UTC, OlingCat commented on locales/zh-CN/teams.ftl
> +governance-team-wg-governance-description = 致力于提升Rust的管理机制
```suggestion
governance-team-wg-governance-description = 致力于提升 Rust 的管理机制。
```

2019-05-29 13:02 UTC, OlingCat commented on locales/zh-CN/teams.ftl
> +governance-team-wg-unsafe-code-guidelines-name = 不安全代码方针 (UCG)
```suggestion
governance-team-wg-unsafe-code-guidelines-name = 不安全代码方针（UCG）
```

2019-05-29 13:02 UTC, OlingCat commented on locales/zh-CN/teams.ftl
> +governance-team-wg-unsafe-code-guidelines-description = 编写"不安全代码方针"--定义了不安全的代码中允许和不允许的行为。
```suggestion
governance-team-wg-unsafe-code-guidelines-description = 编写“不安全代码方针”——定义了不安全的代码中允许和不允许的行为。
```

2019-05-29 13:02 UTC, OlingCat commented on locales/zh-CN/teams.ftl
> +governance-team-wg-embedded-description = 专注于在资源寿险环境以及非传统平台上使用Rust的端到端体验。
```suggestion
governance-team-wg-embedded-description = 专注于在资源受限的环境中和非传统平台上使用 Rust 的端到端体验。
```

2019-05-29 13:02 UTC, OlingCat commented on locales/zh-CN/teams.ftl
> +governance-team-crates-io-name = Crates.io团队
```suggestion
governance-team-crates-io-name = Crates.io 团队
```

2019-05-29 13:02 UTC, OlingCat commented on locales/zh-CN/teams.ftl
> +governance-team-crates-io-description = 管理crates.io的运营，发展以及相关政策。
```suggestion
governance-team-crates-io-description = 管理 crates.io 的运维、开发和相关政策。
```

2019-05-29 13:02 UTC, OlingCat commented on locales/zh-CN/teams.ftl
> +governance-team-community-rustbridge-name = RustBridge团队
```suggestion
governance-team-community-rustbridge-name = RustBridge 团队
```

2019-05-29 13:02 UTC, OlingCat commented on locales/zh-CN/teams.ftl
> +governance-team-community-rustbridge-description = 主要目的是将那些不具代表性的小众人群纳入Rust的包容性教育计划。
```suggestion
governance-team-community-rustbridge-description = 主要目的是将那些不具代表性的小众人群纳入 Rust 的包容性教育计划。
```

2019-05-29 13:02 UTC, OlingCat commented on locales/zh-CN/teams.ftl
> +governance-team-libs-description = Rust标准库，rust-lang包，惯例以及生态的支持。
```suggestion
governance-team-libs-description = Rust 标准库、rust-lang 包、代码约定以及生态的支持。
```

2019-05-29 13:02 UTC, OlingCat commented on locales/zh-CN/teams.ftl
> +governance-team-wg-llvm-description = 和LLVM上游共同开发以推进Rust自身的发展。
```suggestion
governance-team-wg-llvm-description = 和 LLVM 上游共同开发以推进 Rust 自身的发展。
```

2019-05-29 13:02 UTC, OlingCat commented on locales/zh-CN/teams.ftl
> +governance-team-wg-grammar-description = 编写Rust的官方正式语法，并根据现有的实现进行验证。
```suggestion
governance-team-wg-grammar-description = 编写 Rust 的官方正式语法，并根据现有的实现进行验证。
```

2019-05-29 13:02 UTC, OlingCat commented on locales/zh-CN/teams.ftl
> +governance-team-mods-discourse-description = 审核users.rust-lang.org和internals.rust-lang.org
```suggestion
governance-team-mods-discourse-description = 审核 users.rust-lang.org 和 internals.rust-lang.org
```

2019-05-29 13:02 UTC, OlingCat commented on locales/zh-CN/teams.ftl
> +governance-team-wg-rfc-2229-description = 使闭包捕获变量的各个字段而不是整个复合变量
```suggestion
governance-team-wg-rfc-2229-description = 使闭包捕获变量的各个字段而不是整个复合变量。
```

2019-05-29 13:02 UTC, OlingCat commented on locales/zh-CN/teams.ftl
> +governance-team-infra-description = Rust项目自身所需的各种基础设施:CI，版本，机器人，指标
```suggestion
governance-team-infra-description = Rust 项目自身所需的各种基础设施：持续集成、版本管理、机器人和性能指标。
```

2019-05-29 13:02 UTC, OlingCat commented on locales/zh-CN/teams.ftl
> +governance-team-community-survey-description = 进行，分析和展示社区调查。
```suggestion
governance-team-community-survey-description = 开展，分析和公布社区调查。
```

2019-05-29 13:02 UTC, OlingCat commented on locales/zh-CN/teams.ftl
> +governance-team-wg-async-await-name = Async-await实现
```suggestion
governance-team-wg-async-await-name = Async-await 实现
```

2019-05-29 13:02 UTC, OlingCat commented on locales/zh-CN/teams.ftl
> +governance-team-wg-async-await-description = 实现async-await
```suggestion
governance-team-wg-async-await-description = 实现 async-await。
```

2019-05-29 13:02 UTC, OlingCat commented on locales/zh-CN/teams.ftl
> +governance-team-wg-parallel-rustc-name = rustc并行编译支持
```suggestion
governance-team-wg-parallel-rustc-name = rustc 并行编译支持
```

2019-05-29 13:02 UTC, OlingCat commented on locales/zh-CN/teams.ftl
> +governance-team-wg-parallel-rustc-description = 让rustc默认支持并行编译
```suggestion
governance-team-wg-parallel-rustc-description = 让 rustc 默认支持并行编译
```

2019-05-29 13:02 UTC, OlingCat commented on locales/zh-CN/teams.ftl
> +governance-team-community-description = 协调并支持活动，运营RustBridge项目，并开展调查。
```suggestion
governance-team-community-description = 协调并支持活动，运营 RustBridge 项目以及开展调查。
```

2019-05-29 13:02 UTC, OlingCat commented on locales/zh-CN/teams.ftl
> +governance-team-wg-pgo-name = 配置优化指南
```suggestion
governance-team-wg-pgo-name = 基于剖析结果的优化
```

2019-05-29 13:02 UTC, OlingCat commented on locales/zh-CN/teams.ftl
> +governance-team-wg-pgo-description = 为rustc实现配置优化指南
```suggestion
governance-team-wg-pgo-description = 为 rustc 实现基于剖析结果的优化。
```

2019-05-29 13:02 UTC, OlingCat commented on locales/zh-CN/teams.ftl
> +governance-team-reference-description = 编写rust参考
```suggestion
governance-team-reference-description = 编写 rust 参考手册。
```

2019-05-29 13:02 UTC, OlingCat commented on locales/zh-CN/teams.ftl
> +governance-team-wg-traits-description = 改进rustc的trait的实现来遵循Chalk方法。
```suggestion
governance-team-wg-traits-description = 改进 rustc 的 trait 实现以遵循 Chalk 方法。
```

2019-05-29 13:02 UTC, OlingCat commented on locales/zh-CN/teams.ftl
> +governance-team-wg-wasm-name = WebAssembly (WASM)工作组
```suggestion
governance-team-wg-wasm-name = WebAssembly（WASM）工作组
```

2019-05-29 13:02 UTC, OlingCat commented on locales/zh-CN/teams.ftl
> +governance-team-wg-wasm-description = 专注于在JS库和应用中通过WebAssembly嵌入Rust代码的端到端体验。
```suggestion
governance-team-wg-wasm-description = 专注于在 JS 库和应用中通过 WebAssembly 嵌入 Rust 代码的端到端体验。
```

2019-05-29 13:02 UTC, OlingCat commented on locales/zh-CN/teams.ftl
> +governance-team-release-description = 跟踪回归，稳定和生成Rust版本
```suggestion
governance-team-release-description = 跟踪回归测试，稳定化并生成 Rust 发布版。
```

2019-05-29 13:02 UTC, OlingCat commented on locales/zh-CN/teams.ftl
> +governance-team-wg-rustfix-name = Rustfix工作组
```suggestion
governance-team-wg-rustfix-name = Rustfix 工作组
```

2019-05-29 13:02 UTC, OlingCat commented on locales/zh-CN/teams.ftl
> +governance-team-wg-rustfix-description = 改进cargo-fix并作为其他团队之间的一个联络点。
```suggestion
governance-team-wg-rustfix-description = 改进 cargo-fix 并作为其他团队之间的一个联络点。
```

2019-05-29 13:02 UTC, OlingCat commented on locales/zh-CN/teams.ftl
> +governance-team-wg-self-profile-description = 改进-Z self-profile功能
```suggestion
governance-team-wg-self-profile-description = 改进“-Z self-profile”功能。
```

2019-05-29 13:02 UTC, OlingCat commented on locales/zh-CN/teams.ftl
> +governance-team-mods-discord-name = Discord管理员
```suggestion
governance-team-mods-discord-name = Discord 管理员
```

2019-05-29 13:02 UTC, OlingCat commented on locales/zh-CN/teams.ftl
> +governance-team-mods-discord-description = 管理Discord服务器
```suggestion
governance-team-mods-discord-description = 管理 Discord 服务器
```

2019-05-29 13:02 UTC, OlingCat commented on locales/zh-CN/teams.ftl
> +governance-team-rust-by-example-name = Rust by Example团队
```suggestion
governance-team-rust-by-example-name = 《跟着例子学 Rust》团队
```

2019-05-29 13:02 UTC, OlingCat commented on locales/zh-CN/teams.ftl
> +governance-team-rust-by-example-description = 维护并更新Rust By Example
```suggestion
governance-team-rust-by-example-description = 维护并更新《跟着例子学 Rust》
```

2019-05-29 13:02 UTC, OlingCat commented on locales/zh-CN/teams.ftl
> +governance-team-wg-rustup-name = Rustup工作组
```suggestion
governance-team-wg-rustup-name = Rustup 工作组
```

2019-05-29 13:02 UTC, OlingCat commented on locales/zh-CN/teams.ftl
> +governance-team-wg-rustup-description = 设计和实现Rustup
```suggestion
governance-team-wg-rustup-description = 设计和实现 Rustup
```

2019-05-29 13:02 UTC, OlingCat commented on locales/zh-CN/teams.ftl
> +governance-team-operations-description = 处理版本，机器人，基础设施等。
```suggestion
governance-team-operations-description = 处理版本发布，机器人和基础设施等等。
```

2019-05-29 13:02 UTC, OlingCat commented on locales/zh-CN/teams.ftl
> +governance-team-wg-nll-name = 非作用域生命周期 (NLL)
```suggestion
governance-team-wg-nll-name = 非作用域生命周期（NLL）
```

2019-05-29 13:02 UTC, OlingCat commented on locales/zh-CN/teams.ftl
> +governance-team-wg-nll-description = 实现新的基于MIR的借用检查系统以及非作用域生命周期
```suggestion
governance-team-wg-nll-description = 实现新的基于 MIR 的借用检查系统和非词法作用域生命周期。
```

2019-05-29 13:02 UTC, OlingCat commented on locales/zh-CN/teams.ftl
> +governance-team-alumni-name = Rust团队"校友"
```suggestion
governance-team-alumni-name = Rust 团队"校友"
```

2019-05-29 13:02 UTC, OlingCat commented on locales/zh-CN/teams.ftl
> +governance-team-alumni-description = 享受悠闲的退休生活吧
```suggestion
governance-team-alumni-description = 享受悠闲的退休生活吧！
```

2019-05-29 13:03 UTC, OlingCat requested changes
以规范中英文间的空格和标点为主，部分语句略有润色。

2019-05-29 13:06 UTC, OlingCat commented
发现官方介绍的首字母大小写不一致，有的句子后面有句号，有的没有。咱不太了解英文习惯，要不要记录一下？@Zhanghandong

2019-05-29 14:53 UTC, ZhangHanDong commented
@OlingCat 按中文习惯翻译就好了。英文的他们有人会自己润色。如果你愿意，可以去源仓库给官方的人提一下。

2019-05-30 04:41 UTC, OlingCat commented
@readlnh 乃可以在 [Files changed](https://github.com/rust-lang-cn/www.rust-lang.org/pull/27/files) 页面上批量添加接受的修改建议，然后一次提交，

2019-05-30 05:45 UTC, crlf0710 commented on locales/zh-CN/teams.ftl
> +governance-team-wg-net-async-name = 基础异步工作组
=> 异步基础 
与“异步生态"相对

2019-05-30 05:58 UTC, crlf0710 commented on locales/zh-CN/teams.ftl
> +governance-team-alumni-name = Rust团队"校友"
校友的意思不对…… 考虑换个词？比如：离任者、养老会、之类的

2019-05-30 05:59 UTC, crlf0710 commented on locales/zh-CN/teams.ftl
> +governance-team-operations-name = 运营团队
运维团队

2019-05-30 06:00 UTC, crlf0710 commented on locales/zh-CN/teams.ftl
> +governance-team-wg-nll-name = 非作用域生命周期 (NLL)
如果在词法 和 作用域里留一个词的话，还是留词法比较对

2019-05-30 06:03 UTC, crlf0710 commented on locales/zh-CN/teams.ftl
> +governance-team-mods-discord-description = 管理Discord服务器
管理容易被错误理解为运维，主持大概更贴切一点？

2019-05-30 06:24 UTC, readlnh commented
> @readlnh 乃可以在 [Files changed](https://github.com/rust-lang-cn/www.rust-lang.org/pull/27/files) 页面上批量添加接受的修改建议，然后一次提交，

才发现orz...

2019-05-30 06:28 UTC, readlnh commented on locales/zh-CN/teams.ftl
> +governance-team-wg-net-async-name = 基础异步工作组
aaa

2019-05-30 06:36 UTC, readlnh commented on locales/zh-CN/teams.ftl
> +governance-team-wg-net-async-name = 基础异步工作组
```suggestion
governance-team-wg-net-async-name = 异步基础工作组
```

2019-05-30 07:01 UTC, readlnh commented on locales/zh-CN/teams.ftl
> +governance-team-wg-nll-name = 非作用域生命周期 (NLL)
> 如果在词法 和 作用域里留一个词的话，还是留词法比较对

那么翻译成 非词法生命周期 吗？这个地方说实话有点难拿捏，这里应该指的是不需要标注就可以实现生命周期的意思吧？

2019-05-30 09:15 UTC, its404 commented
> 发现官方介绍的首字母大小写不一致，有的句子后面有句号，有的没有。咱不太了解英文习惯，要不要记录一下？@ZhangHanDong

大小写那个部分是在按钮里边的，页面css加了`text-transform`转大写，这种的问题不大。句号的问题，我感觉我们这边还是统一一下，要么全加句号，要么全去掉吧。

2019-05-30 10:36 UTC, readlnh commented on locales/zh-CN/teams.ftl
> +governance-team-wg-nll-name = 非作用域生命周期（NLL）
```suggestion
governance-team-wg-nll-name = 非词法作用域生命周期（NLL）
```

2019-05-30 10:42 UTC, readlnh commented on locales/zh-CN/teams.ftl
> +governance-team-operations-name = 运营团队
```suggestion
governance-team-operations-name = 运维团队
```

2019-05-31 19:29 UTC, aaranxu commented on locales/zh-CN/teams.ftl
> +governance-team-rust-by-example-name = 《跟着例子学 Rust》团队
```suggestion
governance-team-rust-by-example-name = 《通过例子学 Rust》团队
```

本书已经有较为流行译法，统一官方书籍名称翻译

2019-05-31 19:29 UTC, aaranxu commented on locales/zh-CN/teams.ftl
> +governance-team-rust-by-example-description = 维护并更新《跟着例子学 Rust》
```suggestion
governance-team-rust-by-example-description = 维护并更新《通过例子学 Rust》
```

2019-06-01 12:39 UTC, aaranxu commented on locales/zh-CN/teams.ftl
> +governance-team-wg-learning-description = 确保 rustc 指南和 API 文档的“完整行”，让学习编译器变得更简单。
```suggestion
governance-team-wg-learning-description = 确保 rustc 指南和 API 文档的“完整”，让学习编译器变得更简单。
```

2019-06-01 12:39 UTC, aaranxu commented on locales/zh-CN/teams.ftl
> +governance-team-reference-name = 参考团队
```suggestion
governance-team-reference-name = 参考手册团队
```

2019-06-04 12:10 UTC, OlingCat approved these changes

2019-06-04 12:11 UTC, merged