Translate locales/zh-CN/code-of-conduct.ftl to Chinese
rust-lang-cn/www.rust-lang.org pull request #28
Opened 2019-05-28 07:01 UTC by b41sh

[#25 ](https://github.com/rust-lang-cn/www.rust-lang.org/issues/25)

2019-05-28 09:03 UTC, Linger2 commented
thread 'main' panicked at 'File did not parse!: (FluentResource(FluentResource { string: "### Translation file for page: https://www.rust-lang.org/policies/code-of-conduct\ 
...
...
Entry(Message(Message { id: Identifier { name: "coc-moderation-description-team-anchor-text" }, value: Some(Pattern { elements: [TextElement("Rust审核小组")] }), attributes: [], comment: None }))] } }), [ParserError { pos: (1622, 1623), slice: Some((188, 1956)), kind: ExpectedCharRange { range: "a-zA-Z" } }, ParserError { pos: (2236, 2237), slice: Some((2098, 4985)), kind: ExpectedCharRange { range: "a-zA-Z" } }])', src/libcore/result.rs:999:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

2019-05-28 09:37 UTC, ZhangHanDong commented
@b41sh @Linger2  这个估计是文件编码错误

2019-05-28 14:45 UTC, b41sh commented
已修复 @ZhangHanDong

2019-05-29 13:43 UTC, Linger2 commented on locales/zh-CN/code-of-conduct.ftl
> +          <li>请将非结构化的批判保持在最低限度。如果你有坚定的想法想要试验，拉一个分支，看看它是如何工作的。</li>
unstructured critique -> 非结构化的批判 -> 无条理的批判 ?

2019-05-29 13:51 UTC, Linger2 commented on locales/zh-CN/cli.ftl
> +cli-production-sentry-link = Rust使用Sentry &ndash; PolyConf 2017
"Rust使用Sentry" -> "Rust 在 Sentry 中的使用"，看源视频简介大概是这么个意思，The usage of Rust started as an experiment at Sentry but became a non negligible part of our infrastructure.  也觉得可以不用翻译

2019-05-29 13:53 UTC, Linger2 commented on locales/zh-CN/cli.ftl
> +        我们喜欢Rust的原因之一是crates.io的生态。[...]
"我们喜欢Rust的原因之一是crates.io的生态。" -> "我们喜欢 Rust 的其中一个原因是 crates.io 的生态。" ？

2019-05-29 13:55 UTC, Linger2 commented on locales/zh-CN/cli.ftl
> +        已经有很多非常好的基础设施用于构建很好的命令行界面。
"已经有很多非常好的基础设施用于构建很好的命令行界面。" -> "那里面已经有很多非常好的基础设施用于构建很好的命令行界面。"

2019-05-29 13:55 UTC, Linger2 commented on locales/zh-CN/cli.ftl
> +cli-maintainable-errors-link = Rust的错误处理
"Rust的错误处理" -> " Rust 的错误处理"

2019-05-29 13:59 UTC, Linger2 commented on locales/zh-CN/cli.ftl
> +cli-maintainable-errors-heading = 捕获错误 <em>现在</em>
"捕获错误 <em>现在</em>" -> " <em>立即</em>捕获错误" ？

2019-05-29 14:01 UTC, Linger2 commented on locales/zh-CN/cli.ftl
> +cli-maintainable-refactoring-img-alt = cli不是火箭科学
这是个 Easily extend later 上面的火箭图片的 image alt 可以不用翻译

2019-05-29 14:02 UTC, Linger2 commented
各种 image alt 应该可以不用翻译？

2019-05-29 14:24 UTC, zekexiao requested changes

2019-05-29 14:24 UTC, Linger2 commented on locales/zh-CN/cli.ftl
> +cli-pitch-solid-link = Rust的担保
”Rust的担保“ -> “Rust 的保证”

2019-05-29 14:24 UTC, Linger2 commented on locales/zh-CN/cli.ftl
> +cli-pitch-heading = 为什么是Rust?
"为什么是Rust?" -> "为什么是 Rust ？"

2019-05-29 14:24 UTC, Linger2 commented on locales/zh-CN/cli.ftl
> +cli-pitch-manuals-heading = 手册? 已完成
"手册? 已完成" -> "手册？完事了" （hhhh）-> "文档？已完成"；  这里是手册是不是文档的意思？

2019-05-29 14:24 UTC, Linger2 commented on locales/zh-CN/cli.ftl
> +cli-pitch-ship-link = 如何发布Rust代码
"如何发布Rust代码" -> "如何发布 Rust 代码"

2019-05-29 14:24 UTC, Linger2 commented on locales/zh-CN/cli.ftl
> +cli-pitch-machines-description = 除了与人交谈外，Rust还有很棒的工具可以帮助你与机器交谈。
"除了与人交谈外，Rust还有很棒的工具可以帮助你与机器交谈。" -> "除了与人交谈外， Rust 还有很棒的工具可以帮助你与机器交谈。"

2019-05-29 14:24 UTC, Linger2 commented on locales/zh-CN/cli.ftl
> +        Rust会在你运行程序之前指出这些“假设”情况。
"Rust会在你运行程序之前指出这些“假设”情况。" -> " Rust 会在你运行程序之前就找出这些 “假设”情况。"？

2019-05-29 14:24 UTC, Linger2 commented on locales/zh-CN/cli.ftl
> +cli-maintainable-refactoring-heading = 易于后续扩展
"Easily extend later" 对比前面的 "Catch errors now" 我觉得可以翻译成，"后续扩展简单"

2019-05-29 14:24 UTC, Linger2 commented on locales/zh-CN/code-of-conduct.ftl
> +coc-conduct-description-team-anchor-text = Rust审核小组
"Rust审核小组" -> "Rust 审核小组"

2019-05-29 14:24 UTC, Linger2 commented on locales/zh-CN/code-of-conduct.ftl
> +        <p>在Rust社区，我们努力进一步的互相照顾。不要只关注在技术上无懈可击，尽量做好你自己。特别是，避免陷入攻击性或敏感性问题的纠缠，尤其是如果他们偏离主题；这通常会导致不必要的斗争，伤害情感，损害信任；更糟糕的是，它会将人们驱离社区。</p>
"在Rust社区，我们努力进一步的互相照顾。" -> "在 Rust 社区，我们努力进一步的互相照顾。"

2019-05-29 14:24 UTC, Linger2 commented on locales/zh-CN/code-of-conduct.ftl
> +coc-moderation-description-team-anchor-text = Rust审核小组
"Rust审核小组" -> "Rust 审核小组"

2019-05-29 14:55 UTC, ZhangHanDong commented on locales/zh-CN/code-of-conduct.ftl
> +          <li>请将非结构化的批判保持在最低限度。如果你有坚定的想法想要试验，拉一个分支，看看它是如何工作的。</li>
无理批判

2019-05-29 14:56 UTC, ZhangHanDong commented on locales/zh-CN/cli.ftl
> +cli-pitch-heading = 为什么是Rust?
对，注意标点也要改成中文习惯的全角符号。

2019-05-29 15:10 UTC, b41sh commented on locales/zh-CN/cli.ftl
> +cli-pitch-manuals-heading = 手册? 已完成
我觉得应该是手册

2019-05-29 15:39 UTC, zekexiao approved these changes

2019-06-02 07:36 UTC, aaranxu commented
校对完毕，你们也确认下，没问题的话，开始合并 @ZhangHanDong @OlingCat

2019-06-02 10:50 UTC, OlingCat commented
@aaranxu LGTM

2019-06-03 08:22 UTC, merged