Translate locales/zh-CN/security.ftl to Chinese
rust-lang-cn/www.rust-lang.org pull request #30
Opened 2019-05-28 10:37 UTC by starccy

2019-05-28 10:43 UTC, starccy commented
#29

2019-05-29 12:07 UTC, OlingCat requested changes
主要是中英文空格的调整，修改了一些语句表达。

2019-05-29 12:07 UTC, OlingCat commented on locales/zh-CN/security.ftl
> +        <p>安全性是Rust的核心原则之一。为此，我们想确保Rust有一个安全的实现。感谢您花费时间并负责任地报告任何您发现的问题。</p>
```suggestion
        <p>安全性是 Rust 的核心原则之一，为此，我们想确保 Rust 有一个安全的实现。感谢您负责任地花时间报告任何问题。</p>
```
可以不用「您发现的」，在中文语义中已经隐含了。

2019-05-29 12:07 UTC, OlingCat commented on locales/zh-CN/security.ftl
> +        <p>Rust发行版中的所有安全漏洞都应该通过电子邮件报告给 { -security-at-rust-lang-org-anchor }。漏洞清单将会被提交给一个小型的安全团队。您的电子邮件将在24小时内得到确认，随后在48小时内您会通过邮件收到更详细的回复，通知您该错误报告处理的后续步骤。如果您愿意，您也可以使用<a href="{ -rust-security-team-ke
```suggestion
        <p>Rust 发行版中的所有安全漏洞都应该通过电子邮件报告给 { -security-at-rust-lang-org-anchor }。漏洞清单将会被提交给一个小型的安全团队。您的电子邮件将在 24 小时内得到确认，随后在 48 小时内您会收到更详细的邮件回复，通知您该错误报告处理的后续步骤。如果您愿意，也可以使用<a href="{ -rust-security-team-key-href }">我们的公钥</a>来加密您的错误报告。该秘钥也可以在<a href="{ -rust-pgp-key-mit-keyserver-href }">MIT 的密钥服务器</a>上或<a href="#key">本页下方</a>获取。</p>
```

2019-05-29 12:07 UTC, OlingCat commented on locales/zh-CN/security.ftl
> +        <p>这个电子邮箱收到了大量的垃圾邮件，因此，请务必使用具有描述性的主题，以避免我们错过您的报告。在对您的报告进行初步回复后，安全团队将尽力通知您在修复漏洞方面取得的进展。根据<a href="{ -wikipedia-rfpolicy-href }">RFPolicy</a>的建议，这些更新应至少每五天发送一次。实际上，更有可能是每24-48小时发送一次。</p>
```suggestion
        <p>该电子邮箱经常大量的垃圾邮件，因此，请务必使用描述性的主题，以避免我们错过您的报告。在初步回复您的报告后，安全团队会及时通知您该漏洞的修复进展。根据 <a href="{ -wikipedia-rfpolicy-href }">RFPolicy</a> 的建议，这些更新应至少每五天发送一次。实际上，更有可能每 24～48 小时发送一次。</p>
```

2019-05-29 12:07 UTC, OlingCat commented on locales/zh-CN/security.ftl
> +        <p>如果您在48小时内未收到邮件回复，或者在过去五天内未收到安全团队的回复，您可以采取以下几个步骤（按顺序）：</p>
```suggestion
        <p>如果您在 48 小时内未收到邮件回复，或者在未来五天内未收到安全团队的回复，您可以按顺序采取以下步骤：</p>
```
中文的习惯是从发送当天开始往后算。

2019-05-29 12:07 UTC, OlingCat commented on locales/zh-CN/security.ftl
> +          <li>直接联系当前的安全协调员。({ -security-coordinator-email-anchor } (<a href="{ -security-coordinator-public-key-href }">公钥</a>))</li>
```suggestion
          <li>直接联系当前的安全协调员 { -security-coordinator-email-anchor }（<a href="{ -security-coordinator-public-key-href }">公钥</a>）。</li>
```
我们可以直接指明协调员。

2019-05-29 12:07 UTC, OlingCat commented on locales/zh-CN/security.ftl
> +          <li>直接联系备用联系人。({ -backup-security-contact-email-anchor } (<a href="{ -backup-security-contact-public-key-href }">公钥</a>))</li>
```suggestion
          <li>直接联系后备联系人。{ -backup-security-contact-email-anchor }（<a href="{ -backup-security-contact-public-key-href }">公钥</a>）。</li>
```
「备用」一般指物；指人用「后备」，如「后备球员」。

2019-05-29 12:07 UTC, OlingCat commented on locales/zh-CN/security.ftl
> +        <p>Rust项目有5步披露流程。</p>
```suggestion
        <p>Rust 项目有 5 步披露流程：</p>
```

2019-05-29 12:07 UTC, OlingCat commented on locales/zh-CN/security.ftl
> +          <li>收到安全报告，并将其分配给一位主要处理人。此人将协调修复和发布过程。</li>
```suggestion
          <li>收到安全报告后，将其分配给一位主要处理人。此人将协调修复和发布过程。</li>
```

2019-05-29 12:07 UTC, OlingCat commented on locales/zh-CN/security.ftl
> +          <li>过封锁期后，<a href="{ -rustlang-security-announcements-google-groups-forum-href }"> Rust安全邮件列表</a>将发布一份公告副本。这些更改将提交至公共仓库，更新后的程序将部署至rust-lang.org。在收到通知邮件列表的6小时内，Rust博客将发布该通报的副本。</li>
```suggestion
          <li>过封锁期后，<a href="{ -rustlang-security-announcements-google-groups-forum-href }">Rust 安全邮件列表</a>将发布一份公告副本。这些更改会提交至公共仓库，更新后的程序将部署至 rust-lang.org。在收到通知邮件列表的 6 小时内，Rust 博客将发布该通报的副本。</li>
```

2019-05-29 12:07 UTC, OlingCat commented on locales/zh-CN/security.ftl
> +        <p>这个过程可能需要一些时间，尤其是在需要与其他项目的维护人员进行协调时。我们将尽一切努力以尽可能及时的方式处理错误。但是，我们必须遵循上述发布流程，以确保以一致的方式处理披露。</p>
```suggestion
        <p>此过程可能需要一些时间，尤其是在需要与其他项目的维护人员进行协调时。我们将尽一切努力及时处理错误。但是，我们必须遵循上述发布流程，确保能够以一致的方式处理披露。</p>
```

2019-05-29 12:07 UTC, OlingCat commented on locales/zh-CN/security.ftl
> +        <p>接收所有安全公告的最佳方式是订阅<a href="{ -rust-security-announcements-mailing-list-href }">Rust安全公告邮件列表</a> （或者发送电子邮件至{ -rustlang-security-announcements-subscribe-anchor }）。邮件列表的业务量很少，在封禁期过后它将马上收到公共通知。<
```suggestion
        <p>接收所有安全公告的最佳方式是订阅 <a href="{ -rust-security-announcements-mailing-list-href }">Rust 安全公告邮件列表</a>（或发送电子邮件至 { -rustlang-security-announcements-subscribe-anchor }）。邮件列表的业务量很少，在封禁期过后它会马上收到公共通知。</p>
```

2019-05-29 12:07 UTC, OlingCat commented on locales/zh-CN/security.ftl
> +        <p>我们会在封禁期解除前的72小时向{ -distros-openwall-email-anchor }公布漏洞，以便于Linux发行版更新其软件包。</p>
```suggestion
        <p>我们会在封禁期解除前的 72 小时内向 { -distros-openwall-email-anchor } 公布漏洞，以便于 Linux 发行版更新其软件包。</p>
```

2019-05-29 12:07 UTC, OlingCat commented on locales/zh-CN/security.ftl
> +security-pgp-key-heading = 明文PGP密钥
```suggestion
security-pgp-key-heading = 明文 PGP 公钥
```

2019-05-29 12:15 UTC, starccy commented on locales/zh-CN/security.ftl
> +        <p>安全性是Rust的核心原则之一。为此，我们想确保Rust有一个安全的实现。感谢您花费时间并负责任地报告任何您发现的问题。</p>
好的

2019-05-29 12:41 UTC, starccy commented on locales/zh-CN/security.ftl
> +        <p>这个电子邮箱收到了大量的垃圾邮件，因此，请务必使用具有描述性的主题，以避免我们错过您的报告。在对您的报告进行初步回复后，安全团队将尽力通知您在修复漏洞方面取得的进展。根据<a href="{ -wikipedia-rfpolicy-href }">RFPolicy</a>的建议，这些更新应至少每五天发送一次。实际上，更有可能是每24-48小时发送一次。</p>
这个地方貌似漏掉了动词“收到”

2019-05-29 12:53 UTC, OlingCat commented on locales/zh-CN/security.ftl
> +        <p>这个电子邮箱收到了大量的垃圾邮件，因此，请务必使用具有描述性的主题，以避免我们错过您的报告。在对您的报告进行初步回复后，安全团队将尽力通知您在修复漏洞方面取得的进展。根据<a href="{ -wikipedia-rfpolicy-href }">RFPolicy</a>的建议，这些更新应至少每五天发送一次。实际上，更有可能是每24-48小时发送一次。</p>
```suggestion
        <p>该电子邮箱经常收到大量的垃圾邮件，因此，请务必使用描述性的主题，以避免我们错过您的报告。在初步回复您的报告后，安全团队会及时通知您该漏洞的修复进展。根据 <a href="{ -wikipedia-rfpolicy-href }">RFPolicy</a> 的建议，这些更新应至少每五天发送一次。实际上，更有可能每 24～48 小时发送一次。</p>
```
啊，是的。

2019-05-29 12:56 UTC, OlingCat requested changes

2019-05-29 12:56 UTC, OlingCat commented on locales/zh-CN/security.ftl
> +        <p>该电子邮箱经常大量的垃圾邮件，因此，请务必使用描述性的主题，以避免我们错过您的报告。在初步回复您的报告后，安全团队会及时通知您该漏洞的修复进展。根据 <a href="{ -wikipedia-rfpolicy-href }">RFPolicy</a> 的建议，这些更新应至少每五天发送一次。实际上，更有可能每 24～48 小时发送一次。</p>
```suggestion
        <p>该电子邮箱经常收到大量的垃圾邮件，因此，请务必使用描述性的主题，以避免我们错过您的报告。在初步回复您的报告后，安全团队会及时通知您该漏洞的修复进展。根据 <a href="{ -wikipedia-rfpolicy-href }">RFPolicy</a> 的建议，这些更新应至少每五天发送一次。实际上，更有可能每 24～48 小时发送一次。</p>
```

2019-05-29 13:04 UTC, OlingCat approved these changes

2019-05-29 13:09 UTC, merged