Translate locales/zh-CN/policies.ftl into Chinese
rust-lang-cn/www.rust-lang.org pull request #32
Opened 2019-05-28 15:22 UTC by b41sh

[#31 ](https://github.com/rust-lang-cn/www.rust-lang.org/issues/31)

2019-05-30 10:04 UTC, its404 requested changes

2019-05-30 10:04 UTC, its404 commented on locales/zh-CN/policies.ftl
> +policies-reach-out-description = 没找到您要找的东西？有一个问题？请伸出援手！
```suggestion
policies-reach-out-description = 没有找到您要找的内容？有一个问题？请联系我们！
```

2019-05-30 12:32 UTC, b41sh commented on locales/zh-CN/policies.ftl
> +policies-reach-out-description = 没找到您要找的东西？有一个问题？请伸出援手！
:+1:

2019-05-31 19:12 UTC, aaranxu commented on locales/zh-CN/policies.ftl
> +policies-media-guide-link = Logo 政策和媒体指南
```suggestion
policies-media-guide-link = 商标政策和媒体指南
```

根据语境，这里需要翻译成中文，特别指明“商标”的意思

2019-05-31 19:12 UTC, aaranxu commented on locales/zh-CN/policies.ftl
> +policies-reach-out-description = 没有找到您要找的内容？有一个问题？请联系我们！
```suggestion
policies-reach-out-description = 找不到您想要的内容？发现问题？请报告给我们！
```

2019-06-03 03:25 UTC, b41sh commented
@aaranxu @its404 PTAL

2019-06-03 11:44 UTC, aaranxu commented
可以合并 @ZhangHanDong @OlingCat

2019-06-03 11:54 UTC, OlingCat commented
LGTM

2019-06-03 12:10 UTC, its404 commented
没问题了

2019-06-03 12:23 UTC, ZhangHanDong reviewed
有一些建议更改

2019-06-03 12:23 UTC, ZhangHanDong commented on locales/zh-CN/policies.ftl
> +policies-page-description = 此页面链接到一组完备的 Rust 政策。
完备？ 感觉用「完善」更好点
```suggestion
policies-page-description = 此页面链接到一组完善的 Rust 政策。
```

2019-06-03 12:23 UTC, ZhangHanDong commented on locales/zh-CN/policies.ftl
> +policies-code-of-conduct-link = 行为守则
行为准则
```suggestion
policies-code-of-conduct-link = 行为准则
```

2019-06-03 12:23 UTC, ZhangHanDong commented on locales/zh-CN/policies.ftl
> +policies-reach-out-description = 没有找到您要找的内容？有一个问题？请联系我们！
「有一个问题」，这里「一个」没必要翻译。 建议 「有问题？」
```suggestion
policies-reach-out-description = 没有找到您要找的内容？有问题？请联系我们！
```

2019-06-03 12:23 UTC, ZhangHanDong commented on locales/zh-CN/policies.ftl
> +policies-reach-out-link = 给核心团队留言
「致信给核心团队」

2019-06-03 12:23 UTC, ZhangHanDong commented on locales/zh-CN/policies.ftl
> +policies-reach-out-link = 给核心团队留言
```suggestion
policies-reach-out-link = 致信给核心团队
```

2019-06-03 12:23 UTC, ZhangHanDong commented on locales/zh-CN/policies.ftl
> +policies-security-link = 安全信息披露
```suggestion
policies-security-link = 安全信息公示
```

2019-06-03 12:28 UTC, its404 approved these changes

2019-06-04 02:26 UTC, b41sh commented
已修改 @ZhangHanDong @its404 PTAL

2019-06-04 12:10 UTC, merged