Translate locales/zh-CN/licenses.ftl into Chinese #32
rust-lang-cn/www.rust-lang.org pull request #36
Opened 2019-05-29 15:54 UTC by b41sh

[#35 ](https://github.com/rust-lang-cn/www.rust-lang.org/issues/35)

2019-05-30 09:52 UTC, its404 requested changes

2019-05-30 09:52 UTC, its404 commented on locales/zh-CN/licenses.ftl
> +        <p>第三方 logo 可能受其版权和商标的约束，并且不在与 Rust 网站其余部分相同的许可下提供。</p>
```suggestion
        <p>第三方 logo 可能受其版权和商标的约束，不适用于 Rust 网站其他内容的许可。</p>
```

2019-05-30 09:52 UTC, its404 commented on locales/zh-CN/licenses.ftl
> +        图标由来自 <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a> 的 <a href="http://www.freepik.com" title="Freepik">Freepik</a> 制作，由 <a href="http://creativecommons.org/license
```suggestion
        图标由来自 <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a> 的 <a href="http://www.freepik.com" title="Freepik">Freepik</a> 制作，通过 <a href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons BY 3.0">CC-3.0-BY</a> 许可。
```

2019-05-30 09:52 UTC, its404 commented on locales/zh-CN/licenses.ftl
> +        图标由来自 <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a> 的 <a href="http://www.freepik.com" title="Freepik">Freepik</a> 制作，由 <a href="http://creativecommons.org/license
两个“由”貌似有点重叠

2019-05-31 19:24 UTC, aaranxu commented on locales/zh-CN/licenses.ftl
>  licenses-license-general-description =
```suggestion
licenses-license-general-description = Rust 程序设计语言和所有其他官方项目，包括本网站，通常都采取双重许可：
```

2019-05-31 19:24 UTC, aaranxu commented on locales/zh-CN/licenses.ftl
> +        Rust 编程语言和所有其他官方项目，包括本网站，通常都是双重许可的：
```suggestion
```

2019-05-31 19:24 UTC, aaranxu commented on locales/zh-CN/licenses.ftl
> +licenses-apache-v-2-0-link = Apache 许可证, 2.0 版
```suggestion
licenses-apache-v-2-0-link = Apache 2.0 许可证
```

2019-05-31 19:24 UTC, aaranxu commented on locales/zh-CN/licenses.ftl
> +        图标由来自 <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a> 的 <a href="http://www.freepik.com" title="Freepik">Freepik</a> 制作，通过 <a href="http://creativecommons.org/licens
```suggestion
        图标由来自 <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a> 的 <a href="http://www.freepik.com" title="Freepik">Freepik</a> 制作，遵循 <a href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons BY 3.0">CC-3.0-BY</a> 许可协议。
```

2019-06-03 03:24 UTC, b41sh commented
@aaranxu @its404  PTAL

2019-06-03 11:46 UTC, aaranxu commented
可以合并 @ZhangHanDong @OlingCat

2019-06-03 11:50 UTC, OlingCat commented
LGTM
还等 @its404 approve 么= =？

2019-06-03 12:13 UTC, its404 commented
没问题了

2019-06-04 09:38 UTC, its404 approved these changes

2019-06-04 12:10 UTC, merged