Translate locales/zh-CN/media-guide.ftl into Chinese
rust-lang-cn/www.rust-lang.org pull request #37
Opened 2019-06-01 07:56 UTC by OlingCat

2019-06-01 12:49 UTC, aaranxu commented
logo 在这里翻译成 “徽标”，我感觉可能换成 “图标、标志” 可能会更好点

2019-06-02 08:27 UTC, OlingCat commented
> logo 在这里翻译成 “徽标”，我感觉可能换成 “图标、标志” 可能会更好点

用「图标」好了，毕竟还有文字标志

2019-06-03 11:28 UTC, its404 requested changes

2019-06-03 11:28 UTC, its404 commented on locales/zh-CN/media-guide.ftl
> +media-guide-art-license-heading = 艺术作品授权许可
license在之前的license章节只翻译成“许可”了，这块是否也统一一下，去掉“授权”？

2019-06-03 11:28 UTC, its404 commented on locales/zh-CN/media-guide.ftl
> +        <p>Rust 和 Cargo 图标（位图和矢量图）为 Mozilla 所有，按照<a href="https://creativecommons.org/licenses/by/4.0/deed.zh">创作共用-署名（CC-BY）</a>许可协议分发。这是最宽松的创作共用许可协议，它允许用于用于任何目的的重用和修改，其限制是分发者必须“给出适当的署名，提供指向本许可协议的链接
“它允许用于用于任何目的的重用和修改” -> “它允许用于任何目的的重用和修改”，多了一个“用于”。

2019-06-03 11:28 UTC, its404 commented on locales/zh-CN/media-guide.ftl
> +        <p>Rust 和 Cargo 图标（位图和矢量图）为 Mozilla 所有，按照<a href="https://creativecommons.org/licenses/by/4.0/deed.zh">创作共用-署名（CC-BY）</a>许可协议分发。这是最宽松的创作共用许可协议，它允许用于用于任何目的的重用和修改，其限制是分发者必须“给出适当的署名，提供指向本许可协议的链接
“这些图标和 Rust 与 Cargo 名字的使用均受商标法管辖” -> “这些图标和 Rust 与 Cargo 名字的使用均受商标管辖”，这个应该是“商标”，而不是“商标法”？

2019-06-03 11:28 UTC, its404 commented on locales/zh-CN/media-guide.ftl
> +        <p>最基本的原则是，Rust 商标不能出以 Rust 项目或 Mozilla 官方、从属或认可的方式（对一个漫不经心的观察者）出现，除非您得到了 Rust 核心团队的书面授权。这是我们保护用户和开发者免于混淆的基本方式。</p>
“商标不能出以 Rust 项目或 Mozilla 官方、从属或认可的方式（对一个漫不经心的观察者）出现，除非您得到了 Rust 核心团队的书面授权。” -> 除非得到了Rust核心团队的书面授权，否则Rust商标不得以官方、附属或由Rust项目或Mozilla认可的方式（对一个漫不经心的观察者）使用。

2019-06-03 11:28 UTC, its404 commented on locales/zh-CN/media-guide.ftl
> +        <p>有很多用途无需申请明确的批准。<strong>然而，在以下列出的所有情况中，您必须确保 Rust 商标的使用不会以官方认可的方式出现，如上所述。</strong></p>
“很多用途无需申请明确的批准” -> “很多用途无需明确的批准”
“您必须确保 Rust 商标的使用不会以官方认可的方式出现” -> “您必须确保 Rust 商标的使用不会出现“官方”字样”，这个请参考。

2019-06-03 11:28 UTC, its404 commented on locales/zh-CN/media-guide.ftl
> +          <li>精确地声明该软件用 Rust 编程语言编写，兼容 Rust 编程语言，或包含 Rust 编程语言是允许的。在这些情况下，您可以使用 Rust 商标来指明这些而无需事先申请批准。这点均适用于非商业和商业的使用。</li>
“精确地” -> “准确地”？

2019-06-03 11:28 UTC, its404 commented on locales/zh-CN/media-guide.ftl
> +          <li>在非商业产品中使用 Rust 商标，如 RustPostgres 或 Rustymine，或者在如 GitHub 代码库的名字中使用，指出配合 Rust 编程语言使用或适用于 Rust 编程语言均是允许的。这类使用也可以包含 Rust 图标，即便以修改过的形式。对于商业产品（包括众筹或被赞助的），请向 <a href="mailto:trademark@rust-la
“没有以官方认可的方式出现” -> “没有出现“官方”字样”，请参考。

2019-06-03 11:28 UTC, its404 commented on locales/zh-CN/media-guide.ftl
> +          <li>对于免费参加的活动，使用 Rust 商标（即便以修改过的形式）进行聚会，教学等社交活动也是允许的。对于商业活动（包括受赞助的），请通过 <a href="mailto:trademark@rust-lang.org">trademark@rust-lang.org</a> 登记。不过，文字“RustCamp”“RustCon”和“RustConf”没有明确授权不允许使
“由 Rust 项目举行” -> “由 Rust 项目举办”， 请参考。

2019-06-03 11:28 UTC, its404 commented on locales/zh-CN/media-guide.ftl
> +          <li>在网站、小册子、文档、学术论文、书籍和产品包装上使用文字“Rust”来指代 Rust 编程语言也是允许的。</li>
如上这两个“也是允许的”，是否考虑去掉“也”？这些是li列表，每项自称一条。

2019-06-03 11:28 UTC, its404 commented on locales/zh-CN/media-guide.ftl
> +          <li>分发 Rust 编程语言或 Carg 包管理器的修改版并称之为 Rust 或 Cargo 需要来自 Rust 核心团队的明确的，书面的授权。我们通常会允许这些用途，只要这些修改 (1) 相对较小 (2) 非常清楚地传达给最终用户。</li>
“分发 Rust 编程语言或 Carg 包” -> “分发 Rust 编程语言或 Cargo 包”， 少了 “o”

2019-06-03 12:09 UTC, OlingCat commented on locales/zh-CN/media-guide.ftl
> +media-guide-art-license-heading = 艺术作品授权许可
```suggestion
media-guide-art-license-heading = 艺术作品许可
```

2019-06-03 12:09 UTC, OlingCat commented on locales/zh-CN/media-guide.ftl
> +        <p>Rust 和 Cargo 图标（位图和矢量图）为 Mozilla 所有，按照<a href="https://creativecommons.org/licenses/by/4.0/deed.zh">创作共用-署名（CC-BY）</a>许可协议分发。这是最宽松的创作共用许可协议，它允许用于用于任何目的的重用和修改，其限制是分发者必须“给出适当的署名，提供指向本许可协议的链接
```suggestion
        <p>Rust 和 Cargo 图标（位图和矢量图）为 Mozilla 所有，按照<a href="https://creativecommons.org/licenses/by/4.0/deed.zh">创作共用-署名（CC-BY）</a>许可协议分发。这是最宽松的创作共用许可协议，它允许用于任何目的的重用和修改，其限制是分发者必须“给出适当的署名，提供指向本许可协议的链接，同时标明是否（对原始作品）作了修改。”<strong>注意，这些图标和 Rust 与 Cargo 名字的使用均受商标法管辖。我们的商标政策见下</strong>。</p>
```
「商标」作为名词不能管辖，而且查了下这里应该指的就是商标法。
话说乃可以直接用评论上方工具栏中的 suggestion 建议修改，方便看区别，也方便应用更改。

2019-06-03 12:09 UTC, OlingCat commented on locales/zh-CN/media-guide.ftl
> +        <p>最基本的原则是，Rust 商标不能出以 Rust 项目或 Mozilla 官方、从属或认可的方式（对一个漫不经心的观察者）出现，除非您得到了 Rust 核心团队的书面授权。这是我们保护用户和开发者免于混淆的基本方式。</p>
```suggestion
        <p>最基本的原则是，除非得到了 Rust 核心团队的书面授权，否则对于旁观者而言，Rust 商标不得以官方、附属或由 Rust 项目或 Mozilla 认可的方式使用。这是我们保护用户和开发者免于混淆的基本方式。</p>
```
这里的意思应该是：对于任意可能看到这个商标的使用的第三方而言的。乃有啥好的建议？ @its404

2019-06-03 12:09 UTC, OlingCat commented on locales/zh-CN/media-guide.ftl
> +        <p>有很多用途无需申请明确的批准。<strong>然而，在以下列出的所有情况中，您必须确保 Rust 商标的使用不会以官方认可的方式出现，如上所述。</strong></p>
```suggestion
        <p>有很多用途无需明确的批准。<strong>然而，在以下列出的所有情况中，您必须确保 Rust 商标的使用不会出现“官方”字样，如上所述。</strong></p>
```

2019-06-03 12:09 UTC, OlingCat commented on locales/zh-CN/media-guide.ftl
> +          <li>精确地声明该软件用 Rust 编程语言编写，兼容 Rust 编程语言，或包含 Rust 编程语言是允许的。在这些情况下，您可以使用 Rust 商标来指明这些而无需事先申请批准。这点均适用于非商业和商业的使用。</li>
```suggestion
          <li>准确地声明该软件用 Rust 编程语言编写，兼容 Rust 编程语言，或包含 Rust 编程语言是允许的。在这些情况下，您可以使用 Rust 商标来指明这些而无需事先申请批准。这点均适用于非商业和商业的使用。</li>
```

2019-06-03 12:09 UTC, OlingCat commented on locales/zh-CN/media-guide.ftl
> +          <li>在非商业产品中使用 Rust 商标，如 RustPostgres 或 Rustymine，或者在如 GitHub 代码库的名字中使用，指出配合 Rust 编程语言使用或适用于 Rust 编程语言均是允许的。这类使用也可以包含 Rust 图标，即便以修改过的形式。对于商业产品（包括众筹或被赞助的），请向 <a href="mailto:trademark@rust-la
```suggestion
          <li>在非商业产品中使用 Rust 商标，如 RustPostgres 或 Rustymine，或者在如 GitHub 代码库的名字中使用，指出配合 Rust 编程语言使用或适用于 Rust 编程语言均是允许的。这类使用也可以包含 Rust 图标，即便以修改过的形式。对于商业产品（包括众筹或被赞助的），请向 <a href="mailto:trademark@rust-lang.org">trademark@rust-lang.org</a> 登记以确保你的使用没有出现“官方”字样。</li>
```

2019-06-03 12:09 UTC, OlingCat commented on locales/zh-CN/media-guide.ftl
> +          <li>对于免费参加的活动，使用 Rust 商标（即便以修改过的形式）进行聚会，教学等社交活动也是允许的。对于商业活动（包括受赞助的），请通过 <a href="mailto:trademark@rust-lang.org">trademark@rust-lang.org</a> 登记。不过，文字“RustCamp”“RustCon”和“RustConf”没有明确授权不允许使
```suggestion
          <li>对于免费参加的活动，使用 Rust 商标（即便以修改过的形式）进行聚会，教学等社交活动也是允许的。对于商业活动（包括受赞助的），请通过 <a href="mailto:trademark@rust-lang.org">trademark@rust-lang.org</a> 登记。不过，文字“RustCamp”“RustCon”和“RustConf”没有明确授权不允许使用。此外，与上述所有用途一样，若没有书面授权，<strong>活动不能被声明为官方认可或由 Rust 项目举办</strong>。</li>
```

2019-06-03 12:09 UTC, OlingCat commented on locales/zh-CN/media-guide.ftl
> +          <li>在网站、小册子、文档、学术论文、书籍和产品包装上使用文字“Rust”来指代 Rust 编程语言也是允许的。</li>
```suggestion
          <li>在网站、小册子、文档、学术论文、书籍和产品包装上使用文字“Rust”来指代 Rust 编程语言是允许的。</li>
```

2019-06-03 12:09 UTC, OlingCat commented on locales/zh-CN/media-guide.ftl
> +          <li>分发 Rust 编程语言或 Carg 包管理器的修改版并称之为 Rust 或 Cargo 需要来自 Rust 核心团队的明确的，书面的授权。我们通常会允许这些用途，只要这些修改 (1) 相对较小 (2) 非常清楚地传达给最终用户。</li>
```suggestion
          <li>分发 Rust 编程语言或 Cargo 包管理器的修改版并称之为 Rust 或 Cargo 需要来自 Rust 核心团队的明确的，书面的授权。我们通常会允许这些用途，只要这些修改 (1) 相对较小 (2) 非常清楚地传达给最终用户。</li>
```

2019-06-03 12:11 UTC, OlingCat commented
@its404 PTAL

2019-06-03 12:15 UTC, OlingCat commented on locales/zh-CN/media-guide.ftl
> +media-guide-art-license-heading = 艺术作品授权许可
```suggestion
media-guide-art-license-heading = 艺术作品许可
```

2019-06-03 12:35 UTC, its404 commented on locales/zh-CN/media-guide.ftl
> +        <p>最基本的原则是，Rust 商标不能出以 Rust 项目或 Mozilla 官方、从属或认可的方式（对一个漫不经心的观察者）出现，除非您得到了 Rust 核心团队的书面授权。这是我们保护用户和开发者免于混淆的基本方式。</p>
你是说to casual observer么？这个我看的时候也感觉怪怪的，但不知道咋翻译更好呢，先按照你这个来，我也再琢磨下。

2019-06-04 01:40 UTC, its404 requested changes

2019-06-04 01:40 UTC, its404 commented on locales/zh-CN/media-guide.ftl
> +          <li>在书籍或出版物，如“Rust Journal”或“Rust Cookbook”中使用 Rust 商标也是允许的。</li>
```suggestion
          <li>在书籍或出版物，如“Rust Journal”或“Rust Cookbook”中使用 Rust 商标是允许的。</li>
```

2019-06-04 10:22 UTC, its404 commented on locales/zh-CN/media-guide.ftl
> +        <p>最基本的原则是，Rust 商标不能出以 Rust 项目或 Mozilla 官方、从属或认可的方式（对一个漫不经心的观察者）出现，除非您得到了 Rust 核心团队的书面授权。这是我们保护用户和开发者免于混淆的基本方式。</p>
@OlingCat , `to casual observer` 翻译成 `从一个普通人的视角`如何？

2019-06-04 12:07 UTC, OlingCat commented on locales/zh-CN/media-guide.ftl
> +        <p>最基本的原则是，Rust 商标不能出以 Rust 项目或 Mozilla 官方、从属或认可的方式（对一个漫不经心的观察者）出现，除非您得到了 Rust 核心团队的书面授权。这是我们保护用户和开发者免于混淆的基本方式。</p>
> @OlingCat , `to casual observer` 翻译成 `从一个普通人的视角`如何？

可以！

2019-06-04 12:09 UTC, OlingCat commented on locales/zh-CN/media-guide.ftl
> +        <p>最基本的原则是，除非得到了 Rust 核心团队的书面授权，否则对于旁观者而言，Rust 商标不得以官方、附属或由 Rust 项目或 Mozilla 认可的方式使用。这是我们保护用户和开发者免于混淆的基本方式。</p>
```suggestion
        <p>最基本的原则是，除非得到了 Rust 核心团队的书面授权，否则从普通人的视角来看，Rust 商标不得以官方、附属或由 Rust 项目或 Mozilla 认可的方式使用。这是我们保护用户和开发者免于混淆的基本方式。</p>
```

2019-06-04 12:15 UTC, closed without merging