Translate wasm into Chinese.
rust-lang-cn/www.rust-lang.org pull request #54
Opened 2019-06-09 13:43 UTC by OlingCat

2019-06-09 14:49 UTC, huangjj27 requested changes
第一次校对， 发现一些语病问题，补充一些遗漏的翻译的地方。有些地方的翻译还没有定论， 需要进一步探讨。

2019-06-09 14:49 UTC, huangjj27 commented on locales/zh-CN/wasm.ftl
> +        没有垃圾回收不可预测的暂停，也没有 JIT 编译器的性能峭壁，只有底层控制与上层人体工程学的完美结合。
```suggestion
        没有垃圾回收导致不可预测的暂停，也没有 JIT 编译器造成性能峭壁，只有底层控制与上层人体工程学的完美结合。
```

2019-06-09 14:49 UTC, huangjj27 commented on locales/zh-CN/wasm.ftl
> +        了解更多关于快速、安全且开放虚拟机调用的 WebAssembly，并阅读其标准。
```suggestion
        了解更多关于快速、安全且开放的虚拟机WebAssembly，并阅读其标准。
```
原文表示有一个虚拟机，有快速，安全，开放的优点， 并叫做WebAssembly. 此处翻译时， WebAssembly作虚拟机的同位语

2019-06-09 14:49 UTC, huangjj27 commented on locales/zh-CN/wasm.ftl
>  wasm-get-started-book-alt = wasm ferris
为何此处没有翻译， 而前面的alt都进行了翻译？

2019-06-09 14:49 UTC, huangjj27 commented on locales/zh-CN/wasm.ftl
> +wasm-js-heading = 配合 JavaScript 使用
似乎没有了“plays well”的感觉， 但是一下子也想不出要如何翻译

2019-06-09 14:49 UTC, huangjj27 commented on locales/zh-CN/wasm.ftl
> +wasm-js-interop-heading = 无缝的互操作性
```suggestion
wasm-js-interop-heading = 无缝互操作
```

2019-06-09 14:49 UTC, huangjj27 commented on locales/zh-CN/wasm.ftl
>          Steven Pack, <a href="{ $href }">Serverless Rust with Cloudflare Workers</a>
此句缺少翻译

2019-06-09 14:49 UTC, huangjj27 commented on locales/zh-CN/wasm.ftl
>  wasm-production-mozilla-alt = firefox
```suggestion
wasm-production-mozilla-alt = 火狐
```

2019-06-09 14:49 UTC, huangjj27 commented on locales/zh-CN/wasm.ftl
> +        （<code>source-map</code> 库的）JavaScript 实现以性能的名义积累了大量复杂的代码，
原文中的方括号可能是连接， 但是没有看到连接指向的地址.
建议暂时这样保留圆括号， 以后要找机会改过来
。

2019-06-09 17:01 UTC, OlingCat commented on locales/zh-CN/wasm.ftl
> +        （<code>source-map</code> 库的）JavaScript 实现以性能的名义积累了大量复杂的代码，
不是连接，只是引用的补充

2019-06-09 17:07 UTC, OlingCat commented on locales/zh-CN/wasm.ftl
> +wasm-js-heading = 配合 JavaScript 使用
```suggestion
wasm-js-heading = JavaScript 的最佳搭档
```
这样如何？

2019-06-09 17:08 UTC, OlingCat commented on locales/zh-CN/wasm.ftl
>  wasm-get-started-book-alt = wasm ferris
这俩词都是名词不用翻译啊= =

2019-06-10 03:44 UTC, ZhangHanDong requested changes

2019-06-10 03:44 UTC, ZhangHanDong commented on locales/zh-CN/wasm.ftl
> +wasm-why-rust-predictable-heading = 可预测的性能
```suggestion
wasm-why-rust-predictable-heading = 可预见的性能
```

2019-06-10 03:44 UTC, ZhangHanDong commented on locales/zh-CN/wasm.ftl
> +        没有垃圾回收导致不可预测的暂停，也没有 JIT 编译器造成性能峭壁，只有底层控制与上层人体工程学的完美结合。
```suggestion
        没有难以预料的 GC 暂停，也没有 JIT 编译器造成性能抖动，只有底层控制与上层人体工程学的完美结合。
```

2019-06-10 03:44 UTC, ZhangHanDong commented on locales/zh-CN/wasm.ftl
> +        更少的代码意味着更快的页面加载速度。Rust 生成的 <code>.wasm</code> 不含垃圾回收器等累赘。高级优化和摇树优化可移除死代码。
```suggestion
        代码尺寸越小，页面加载速度就越快。Rust 生成的 <code>.wasm</code> 模块不含类似于垃圾回收器这样的额外成本。高级优化和 tree shaking 优化可移除无用代码。
```

2019-06-10 03:44 UTC, ZhangHanDong commented on locales/zh-CN/wasm.ftl
> +wasm-why-rust-small-code-heading = 更少的代码
```suggestion
wasm-why-rust-small-code-heading = 代码尺寸更小
```

2019-06-10 03:44 UTC, ZhangHanDong commented on locales/zh-CN/wasm.ftl
> +        充满活力的库生态系统助您旗开得胜。Rust 拥有丰富的表达能力和零成本抽象。友好的社区可帮助您学习。
```suggestion
        充满活力的库生态系统助您旗开得胜。Rust 拥有丰富的表达能力和零成本的抽象，以及助力您学习的友好社区。
```

2019-06-10 03:44 UTC, ZhangHanDong commented on locales/zh-CN/wasm.ftl
> +        了解更多关于快速、安全且开放的虚拟机WebAssembly，并阅读其标准。
```suggestion
        了解更多关于快速、安全和开放的WebAssembly虚拟机信息，并阅读其标准。
```

2019-06-10 03:44 UTC, ZhangHanDong commented on locales/zh-CN/wasm.ftl
>  wasm-get-started-book-alt = wasm ferris
```suggestion
wasm-get-started-book-alt = wasm 和 Rust吉祥物
```

2019-06-10 03:44 UTC, ZhangHanDong commented on locales/zh-CN/wasm.ftl
> +wasm-js-augment-heading = 补充，而非取代
```suggestion
wasm-js-augment-heading = 增强，而非取代
```

2019-06-10 03:44 UTC, ZhangHanDong commented on locales/zh-CN/wasm.ftl
> +        WebAssembly 的梦想不是杀死 JavaScript，而是与其并存。得益于 Rust 对性能的专注，WASM 可为重度处理或底层任务助力。
```suggestion
        WebAssembly 的梦想不是扼杀 JavaScript，而是与其并存，来帮助处理繁重或底层的一些任务。Rust以性能为先，这些任务也可以受益。
```

2019-06-10 03:44 UTC, ZhangHanDong commented on locales/zh-CN/wasm.ftl
> +        Steven Pack，<a href="{ $href }">Serverless Rust 与 Cloudflare Workers</a>
```suggestion
        Steven Pack，<a href="{ $href }">《Serverless Rust 与 Cloudflare Workers》</a>
```

2019-06-10 03:44 UTC, ZhangHanDong commented on locales/zh-CN/wasm.ftl
> +        {"["}<code>source-map</code> 库的] JavaScript 实现以性能的名义积累了大量复杂的代码，
```suggestion
        {"["}<code>source-map</code> 库的] JavaScript 实现以性能为由累积了大量的复杂代码，
```

2019-06-10 03:44 UTC, ZhangHanDong commented on locales/zh-CN/wasm.ftl
> +        而我们将它替换为惯用的 Rust。Rust 不会强迫我们在明确地表达意图和运行时性能之间做出选择。
```suggestion
        而我们将它替换为地道的 Rust。Rust 不会强迫我们在明确地表达意图和运行时性能之间做出选择。
```

2019-06-10 03:44 UTC, ZhangHanDong commented on locales/zh-CN/wasm.ftl
> +        Nick Fitzgerald，<a href="{ $href }">用 Rust 和 WebAssembly 提升 Source Maps 的性能</a>
```suggestion
        Nick Fitzgerald，<a href="{ $href }">《用 Rust 和 WebAssembly 提升 Source Maps 的性能》</a>
```

2019-06-10 03:44 UTC, ZhangHanDong commented on locales/zh-CN/wasm.ftl
> +        {"["}Rust 的]性质让它很容易通过 WASM 将 DivANS 的编解码器嵌入到 Web 页面中，如前文所述。
```suggestion
        {"["}Rust 的]特性使然，通过 WASM 可以轻松地将 DivANS 编解码器嵌入到网页中，如上所示
```

2019-06-10 03:44 UTC, ZhangHanDong commented on locales/zh-CN/wasm.ftl
> +        Daniel Reiter Horn and Jongmin Baek，<a href="{ $href }">用 DivANS 构建更好的压缩</a>
```suggestion
        Daniel Reiter Horn and Jongmin Baek，<a href="{ $href }">《用 DivANS 构建更好的压缩》</a>
```

2019-06-10 09:44 UTC, merged